// Generated by L3P v1.4 BETA 20131202 (Win32)  (C) 1998-2013 Lars C. Hassing SP.lars@AM.hassings.dk
// L3P website:  http://www.hassings.dk/l3/l3p.html
// LDraw.org:    http://www.ldraw.org
// Date:         Fri Aug 22 22:42:09 2014
// Input file:   D:\Datsville RPG\trunk\povray_source\pov_main_project\items\weapon_021_pharaohstaff.ldr
// Title:        Untitled
// Author:       MLCad
// ModelDir:     D:\Datsville RPG\trunk\povray_source\pov_main_project\items
// WorkDir:      D:\Datsville RPG\trunk\povray_source\pov_main_project\items
// LDRAWDIR:     E:\Programs Windows\LDraw (LDRAWDIR environment variable)
// SearchDirs:   (Default)
// SearchDir1:   D:\Datsville RPG\trunk\povray_source\pov_main_project\items\ (0x10)
// SearchDir2:   E:\Programs Windows\LDraw\P\ (0x9)
// SearchDir3:   E:\Programs Windows\LDraw\PARTS\ (0x4)
// SearchDir4:   E:\Programs Windows\LDraw\MODELS\ (0x0)
// ldconfig.ldr: E:\Programs Windows\LDraw\ldconfig.ldr
// Commandline:  "E:\Programs Windows\l3p14beta\l3p.exe" "D:\Datsville RPG\trunk\povray_source\pov_main_project\items\weapon_021_pharaohstaff.ldr" "D:\Datsville RPG\trunk\povray_source\pov_main_project\items\weapon_021_pharaohstaff.pov" -o -ic -il -ibitems.inc -ieweapons_camera.inc

#if (version < 3.1)
	#error "This POV code requires at least version 3.1\n"
#end

//// Defines

#declare L3Version = 1.4;

#declare L3Quality = 2;  // Quality level, 0=BBox, 1=no refr, 2=normal, 3=studlogo, 4=stud2logo

#declare L3SW = 0.5;  // Width of seam between two bricks

#declare L3Studs = 1;  // 1=on 0=off

#declare L3Bumps = 0;  // 1=on 0=off


#declare L3Ambient = 0.4;
#declare L3Diffuse = 0.4;
#declare L3Ior     = 1.25;
#declare L3NormalBumps = normal { bumps 0.01 scale 20 }
#declare L3NormalSlope = normal { bumps 0.3 scale 0.5 }


#declare L3SWT = (L3SW ? L3SW : 0.001);  // At least a small seam when transparent

#declare L3Logo = union {
	sphere {<-59,0,-96>,6}
	cylinder {<-59,0,-96>,<59,0,-122>,6 open}
	sphere {<59,0,-122>,6}
	cylinder {<59,0,-122>,<59,0,-84>,6 open}
	sphere {<59,0,-84>,6}

	sphere {<-59,0,-36>,6}
	cylinder {<-59,0,-36>,<-59,0,1>,6 open}
	sphere {<-59,0,1>,6}
	cylinder {<0,0,-49>,<0,0,-25>,6 open}
	sphere {<0,0,-25>,6}
	sphere {<59,0,-62>,6}
	cylinder {<59,0,-62>,<59,0,-24>,6 open}
	sphere {<59,0,-24>,6}
	cylinder {<-59,0,-36>,<59,0,-62>,6 open}

	sphere {<-35.95,0,57>,6}
	torus {18.45,6 clipped_by{plane{<40,0,-9>,0}} translate<-40,0,39>}
	cylinder {<-44.05,0,21>,<35.95,0,3>,6 open}
	torus {18.45,6 clipped_by{plane{<-40,0,9>,0}} translate<40,0,21>}
	cylinder {<44.05,0,39>,<0,0,49>,6 open}
	sphere {<0,0,49>,6}
	cylinder {<0,0,49>,<0,0,34>,6 open}
	sphere {<0,0,34>,6}

	torus {18.45,6 clipped_by{plane{<40,0,-9>,0}} translate<-40,0,99>}
	cylinder {<-44.05,0,81>,<35.95,0,63>,6 open}
	torus {18.45,6 clipped_by{plane{<-40,0,9>,0}} translate<40,0,81>}
	cylinder {<44.05,0,99>,<-35.95,0,117>,6 open}

	scale 4.5/128
}


//// IncludeFile AtBeginning
#include "items_settings.inc"



//// Finishes
#ifndef (L3FinishOpaque)
#declare L3FinishOpaque = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.5
		phong_size 40
		reflection 0.08
	#end
}
#end

#ifndef (L3FinishChrome)
#declare L3FinishChrome = finish {
	ambient 0.25
	diffuse 0.6
	#if (L3Quality >= 2)
		brilliance 5
		metallic
		specular 0.80
		roughness 1/100
		reflection 0.65
	#end
}
#end

#ifndef (L3FinishPearlescent)
//Not supported yet, using Opaque
#declare L3FinishPearlescent = finish { L3FinishOpaque }
#end

#ifndef (L3FinishRubber)
#declare L3FinishRubber = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.1
		phong_size 10
		reflection 0
	#end
}
#end

#ifndef (L3FinishMatte_metallic)
//Not supported yet, using Opaque
#declare L3FinishMatte_metallic = finish { L3FinishOpaque }
#end

#ifndef (L3FinishMetal)
//Not supported yet, using Opaque
#declare L3FinishMetal = finish { L3FinishOpaque }
#end

#ifndef (L3FinishTransparent)
#declare L3FinishTransparent = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.5
		phong_size 40
		reflection 0.2
	#end
}
#end



//// Macros
#ifndef (L3TextureOpaqueRGB)
#macro L3TextureOpaqueRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishOpaque }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureChromeRGB)
#macro L3TextureChromeRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishChrome }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TexturePearlescentRGB)
#macro L3TexturePearlescentRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishPearlescent }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureRubberRGB)
#macro L3TextureRubberRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishRubber }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureMatte_metallicRGB)
#macro L3TextureMatte_metallicRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishMatte_metallic }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureMetalRGB)
#macro L3TextureMetalRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishMetal }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureTransparentRGBA)
#macro L3TextureTransparentRGBA(r,g,b,a)
// Alpha -> Filter: 255 -> 1.00, 128 -> 0.85, 0 -> 0
#local f = (a >= 128 ? 0.85 + (a-128) * 0.15 / (255-128) : a * 0.85 / 255);
texture {
	pigment { rgb <r/255,g/255,b/255> #if (L3Quality > 1) filter f #end }
	finish { L3FinishTransparent }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureSlope)
#macro L3TextureSlope(tex)
texture {
	tex
	#if (L3Quality > 1) normal { L3NormalSlope } #end
}
#end
#end

#ifndef (L3Material)
#macro L3Material(tex)
material {
	texture { tex }
}
#end
#end

#ifndef (L3MaterialT)
#macro L3MaterialT(tex)
material {
	texture { tex }
	#if (L3Quality > 1)
		interior { ior L3Ior }
	#end
}
#end
#end



//// Color 7 Light_Gray (from ldconfig.ldr)
#ifndef (L3Texture7)
#declare L3Texture7 = L3TextureOpaqueRGB(155,161,157)
#end
#ifndef (L3Texture7_slope)
#declare L3Texture7_slope = L3TextureSlope(L3Texture7)
#end
#ifndef (L3Color7)
#declare L3Color7 = L3Material(L3Texture7)
#end
#ifndef (L3Color7_slope)
#declare L3Color7_slope = L3Material(L3Texture7_slope)
#end


//// Color 4 Red (from ldconfig.ldr)
#ifndef (L3Texture4)
#declare L3Texture4 = L3TextureOpaqueRGB(201,26,9)
#end
#ifndef (L3Texture4_slope)
#declare L3Texture4_slope = L3TextureSlope(L3Texture4)
#end
#ifndef (L3Color4)
#declare L3Color4 = L3Material(L3Texture4)
#end
#ifndef (L3Color4_slope)
#declare L3Color4_slope = L3Material(L3Texture4_slope)
#end


//// Primitive 4-4disc.dat
#ifndef (_4_dash_4disc_dot_dat)
#declare _4_dash_4disc_dot_dat = disc { <0,0,0>, <0,1,0>, 1 }
#end // ifndef (_4_dash_4disc_dot_dat)


//// Primitive 4-4cyli.dat
#ifndef (_4_dash_4cyli_dot_dat)
#declare _4_dash_4cyli_dot_dat = cylinder { <0,0,0>, <0,1,0>, 1 open }
#end // ifndef (_4_dash_4cyli_dot_dat)


//// Primitive 4-4cylc.dat
#ifndef (_4_dash_4cylc_dot_dat)
#declare _4_dash_4cylc_dot_dat = union {
// Cylinder Closed 1.0
// Name: 4-4cylc.dat
// Author: Alex Taylor [anathema]
// !LDRAW_ORG Primitive UPDATE 2009-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2008-12-29 [cwdee] Removed one disc
// !HISTORY 2009-09-03 [PTadmin] Official Update 2009-02
	object { _4_dash_4disc_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
	object { _4_dash_4cyli_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
}
#end // ifndef (_4_dash_4cylc_dot_dat)


//// Primitive 2-4con4.dat
#ifndef (_2_dash_4con4_dot_dat)
#declare _2_dash_4con4_dot_dat = object {
// Cone  4 x 0.5
// Name: 2-4con4.dat
// Author: Mark Kennedy [mkennedy]
// !LDRAW_ORG Primitive UPDATE 2012-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2009-05-02 [PTadmin] Official Update 2009-01
// !HISTORY 2012-02-16 [Philo] Recreated CCW
// !HISTORY 2012-03-30 [PTadmin] Official Update 2012-01
	mesh {
		triangle { <4,1,0>, <3.6956,1,1.5308>, <4.6195,0,1.9135> }
		triangle { <4.6195,0,1.9135>, <5,0,0>, <4,1,0> }
		triangle { <3.6956,1,1.5308>, <2.8284,1,2.8284>, <3.5355,0,3.5355> }
		triangle { <3.5355,0,3.5355>, <4.6195,0,1.9135>, <3.6956,1,1.5308> }
		triangle { <2.8284,1,2.8284>, <1.5308,1,3.6956>, <1.9135,0,4.6195> }
		triangle { <1.9135,0,4.6195>, <3.5355,0,3.5355>, <2.8284,1,2.8284> }
		triangle { <1.5308,1,3.6956>, <0,1,4>, <0,0,5> }
		triangle { <0,0,5>, <1.9135,0,4.6195>, <1.5308,1,3.6956> }
		triangle { <0,1,4>, <-1.5308,1,3.6956>, <-1.9135,0,4.6195> }
		triangle { <-1.9135,0,4.6195>, <0,0,5>, <0,1,4> }
		triangle { <-1.5308,1,3.6956>, <-2.8284,1,2.8284>, <-3.5355,0,3.5355> }
		triangle { <-3.5355,0,3.5355>, <-1.9135,0,4.6195>, <-1.5308,1,3.6956> }
		triangle { <-2.8284,1,2.8284>, <-3.6956,1,1.5308>, <-4.6195,0,1.9135> }
		triangle { <-4.6195,0,1.9135>, <-3.5355,0,3.5355>, <-2.8284,1,2.8284> }
		triangle { <-3.6956,1,1.5308>, <-4,1,0>, <-5,0,0> }
		triangle { <-5,0,0>, <-4.6195,0,1.9135>, <-3.6956,1,1.5308> }
// conditional lines
// Build by Primitive Generator 2
	}
}
#end // ifndef (_2_dash_4con4_dot_dat)


//// Primitive 2-4disc.dat
#ifndef (_2_dash_4disc_dot_dat)
#declare _2_dash_4disc_dot_dat = disc { <0,0,0>, <0,1,0>, 1 clipped_by { box { <-2,-1,0>, <2,1,2> } } }
#end // ifndef (_2_dash_4disc_dot_dat)


//// Part s\93252s01.dat
#ifndef (s_slash_93252s01_dot_dat)
#declare s_slash_93252s01_dot_dat = #if (L3Quality = 0) box { <-7.5,-48,0>, <7.5,0,19> } #else union {
// ~Minifig Pharaoh's Staff Socket Half with Blade
// Name: s\93252s01.dat
// Author: Christian Neumann [Wesley]
// !LDRAW_ORG Subpart UPDATE 2011-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2011-12-29 [PTadmin] Official Update 2011-02
// -- blade, first half --
// left
	mesh {
		triangle { <1.75,-43,12>, <1.75,-46.55,6.93>, <1.6,-46.19,6.91> }
		triangle { <1.75,-43,12>, <1.6,-46.19,6.91>, <0,-43.19,7.41> }
		triangle { <1.75,-43,12>, <0,-43.19,7.41>, <0,-43,7.5> }
		triangle { <1.75,-40,14>, <1.75,-43,12>, <0,-43,7.5> }
		triangle { <0,-43,7.5>, <0,-40,10.3>, <1.75,-40,14> }
		triangle { <1.75,-35,15>, <1.75,-40,14>, <0,-40,10.3> }
		triangle { <1.75,-35,15>, <0,-40,10.3>, <0,-35,11.5> }
		triangle { <1.75,-30,15>, <1.75,-35,15>, <0,-35,11.5> }
		triangle { <1.75,-30,15>, <0,-35,11.5>, <0,-30,11> }
		triangle { <1.75,-25,14>, <1.75,-30,15>, <0,-30,11> }
		triangle { <1.75,-25,14>, <0,-30,11>, <0,-25,9.5> }
		triangle { <1.75,-20,11.5>, <1.75,-25,14>, <0,-25,9.5> }
		triangle { <1.75,-20,11.5>, <0,-25,9.5>, <0,-20,6.62> }
		triangle { <1.75,-15,8.5>, <1.75,-20,11.5>, <0,-20,6.62> }
		triangle { <0,-20,6.62>, <0,-17.5,5>, <1.75,-15,8.5> }
		triangle { <0,-17.5,5>, <1.75,-12,6.6>, <1.75,-15,8.5> }
		triangle { <1.75,-10,5>, <1.75,-12,6.6>, <0,-17.5,5> }
// right
		triangle { <1.75,-43,12>, <1.6,-46.82,7.09>, <1.75,-46.55,6.93> }
		triangle { <1.75,-43,12>, <0,-48,10>, <1.6,-46.82,7.09> }
		triangle { <0,-47.96,10.25>, <0,-48,10>, <1.75,-43,12> }
		triangle { <1.75,-43,12>, <0,-45.14,14.1>, <0,-47.96,10.25> }
		triangle { <0,-40,17.5>, <0,-45.14,14.1>, <1.75,-43,12> }
		triangle { <1.75,-40,14>, <0,-40,17.5>, <1.75,-43,12> }
		triangle { <0,-35,19>, <0,-40,17.5>, <1.75,-40,14> }
		triangle { <1.75,-35,15>, <0,-35,19>, <1.75,-40,14> }
		triangle { <0,-30,19>, <0,-35,19>, <1.75,-35,15> }
		triangle { <1.75,-30,15>, <0,-30,19>, <1.75,-35,15> }
		triangle { <0,-25,18>, <0,-30,19>, <1.75,-30,15> }
		triangle { <1.75,-25,14>, <0,-25,18>, <1.75,-30,15> }
		triangle { <0,-20,16>, <0,-25,18>, <1.75,-25,14> }
		triangle { <1.75,-20,11.5>, <0,-20,16>, <1.75,-25,14> }
		triangle { <0,-15,13>, <0,-20,16>, <1.75,-20,11.5> }
		triangle { <1.75,-15,8.5>, <0,-15,13>, <1.75,-20,11.5> }
		triangle { <1.75,-12,6.6>, <0,-15,13>, <1.75,-15,8.5> }
		triangle { <0,-9,8>, <0,-15,13>, <1.75,-12,6.6> }
		triangle { <0,-9,8>, <1.75,-12,6.6>, <1.75,-10,5> }
		triangle { <0,-3.25,5>, <0,-9,8>, <1.75,-10,5> }
		triangle { <1.75,-10,5>, <0.75,-3.25,3.536>, <0,-3.25,5> }
// outer edges
// inner edges
// 
// -- blade second half --
// left
		triangle { <-1.6,-46.19,6.91>, <-1.75,-46.55,6.93>, <-1.75,-43,12> }
		triangle { <0,-43.19,7.41>, <-1.6,-46.19,6.91>, <-1.75,-43,12> }
		triangle { <0,-43,7.5>, <0,-43.19,7.41>, <-1.75,-43,12> }
		triangle { <0,-43,7.5>, <-1.75,-43,12>, <-1.75,-40,14> }
		triangle { <-1.75,-40,14>, <0,-40,10.3>, <0,-43,7.5> }
		triangle { <0,-40,10.3>, <-1.75,-40,14>, <-1.75,-35,15> }
		triangle { <0,-35,11.5>, <0,-40,10.3>, <-1.75,-35,15> }
		triangle { <0,-35,11.5>, <-1.75,-35,15>, <-1.75,-30,15> }
		triangle { <0,-30,11>, <0,-35,11.5>, <-1.75,-30,15> }
		triangle { <0,-30,11>, <-1.75,-30,15>, <-1.75,-25,14> }
		triangle { <0,-25,9.5>, <0,-30,11>, <-1.75,-25,14> }
		triangle { <0,-25,9.5>, <-1.75,-25,14>, <-1.75,-20,11.5> }
		triangle { <0,-20,6.62>, <0,-25,9.5>, <-1.75,-20,11.5> }
		triangle { <0,-20,6.62>, <-1.75,-20,11.5>, <-1.75,-15,8.5> }
		triangle { <-1.75,-15,8.5>, <0,-17.5,5>, <0,-20,6.62> }
		triangle { <-1.75,-15,8.5>, <-1.75,-12,6.6>, <0,-17.5,5> }
		triangle { <0,-17.5,5>, <-1.75,-12,6.6>, <-1.75,-10,5> }
// right
		triangle { <-1.75,-46.55,6.93>, <-1.6,-46.82,7.09>, <-1.75,-43,12> }
		triangle { <-1.6,-46.82,7.09>, <0,-48,10>, <-1.75,-43,12> }
		triangle { <-1.75,-43,12>, <0,-48,10>, <0,-47.96,10.25> }
		triangle { <0,-47.96,10.25>, <0,-45.14,14.1>, <-1.75,-43,12> }
		triangle { <-1.75,-43,12>, <0,-45.14,14.1>, <0,-40,17.5> }
		triangle { <-1.75,-43,12>, <0,-40,17.5>, <-1.75,-40,14> }
		triangle { <-1.75,-40,14>, <0,-40,17.5>, <0,-35,19> }
		triangle { <-1.75,-40,14>, <0,-35,19>, <-1.75,-35,15> }
		triangle { <-1.75,-35,15>, <0,-35,19>, <0,-30,19> }
		triangle { <-1.75,-35,15>, <0,-30,19>, <-1.75,-30,15> }
		triangle { <-1.75,-30,15>, <0,-30,19>, <0,-25,18> }
		triangle { <-1.75,-30,15>, <0,-25,18>, <-1.75,-25,14> }
		triangle { <-1.75,-25,14>, <0,-25,18>, <0,-20,16> }
		triangle { <-1.75,-25,14>, <0,-20,16>, <-1.75,-20,11.5> }
		triangle { <-1.75,-20,11.5>, <0,-20,16>, <0,-15,13> }
		triangle { <-1.75,-20,11.5>, <0,-15,13>, <-1.75,-15,8.5> }
		triangle { <-1.75,-15,8.5>, <0,-15,13>, <-1.75,-12,6.6> }
		triangle { <-1.75,-12,6.6>, <0,-15,13>, <0,-9,8> }
		triangle { <-1.75,-10,5>, <-1.75,-12,6.6>, <0,-9,8> }
		triangle { <-1.75,-10,5>, <0,-9,8>, <0,-3.25,5> }
		triangle { <0,-3.25,5>, <-0.75,-3.25,3.536>, <-1.75,-10,5> }
// outer edges
// inner edges
// 
// blade tip surface
		triangle { <1.6,-46.19,6.91>, <-1.6,-46.19,6.91>, <0,-43.19,7.41> }
		triangle { <1.75,-46.55,6.93>, <-1.75,-46.55,6.93>, <-1.6,-46.19,6.91> }
		triangle { <-1.6,-46.19,6.91>, <1.6,-46.19,6.91>, <1.75,-46.55,6.93> }
		triangle { <1.6,-46.82,7.09>, <-1.6,-46.82,7.09>, <-1.75,-46.55,6.93> }
		triangle { <-1.75,-46.55,6.93>, <1.75,-46.55,6.93>, <1.6,-46.82,7.09> }
		triangle { <0,-48,10>, <-1.6,-46.82,7.09>, <1.6,-46.82,7.09> }
// outer common edges
// blade/socket edges
// socket, upper half right
		triangle { <3.6956,-17.5,1.5308>, <4,-17.5,0>, <5,-17.5,0> }
		triangle { <5,-17.5,0>, <3.5,-17.5,3.5>, <3.6956,-17.5,1.5308> }
		triangle { <3.6956,-17.5,1.5308>, <3.5,-17.5,3.5>, <2.8284,-17.5,2.8284> }
		triangle { <1.5308,-17.5,3.6956>, <2.8284,-17.5,2.8284>, <3.5,-17.5,3.5> }
		triangle { <3.5,-17.5,3.5>, <0,-17.5,5>, <1.5308,-17.5,3.6956> }
		triangle { <1.5308,-17.5,3.6956>, <0,-17.5,5>, <0,-17.5,4> }
		triangle { <7.5,-10.25,3.1>, <5,-17.5,0>, <7.5,-10.25,0> }
		triangle { <7.5,-10.25,3.1>, <3.5,-17.5,3.5>, <5,-17.5,0> }
		triangle { <3.1,-10.25,7.5>, <3.5,-17.5,3.5>, <7.5,-10.25,3.1> }
		triangle { <3.1,-10.25,7.5>, <0,-17.5,5>, <3.5,-17.5,3.5> }
		triangle { <-3.1,-10.25,7.5>, <0,-17.5,5>, <3.1,-10.25,7.5> }
// upper half left
		triangle { <-1.5308,-17.5,3.6956>, <0,-17.5,4>, <0,-17.5,5> }
		triangle { <0,-17.5,5>, <-3.5,-17.5,3.5>, <-1.5308,-17.5,3.6956> }
		triangle { <-1.5308,-17.5,3.6956>, <-3.5,-17.5,3.5>, <-2.8284,-17.5,2.8284> }
		triangle { <-3.6956,-17.5,1.5308>, <-2.8284,-17.5,2.8284>, <-3.5,-17.5,3.5> }
		triangle { <-3.5,-17.5,3.5>, <-5,-17.5,0>, <-3.6956,-17.5,1.5308> }
		triangle { <-3.6956,-17.5,1.5308>, <-5,-17.5,0>, <-4,-17.5,0> }
		triangle { <-3.1,-10.25,7.5>, <-3.5,-17.5,3.5>, <0,-17.5,5> }
		triangle { <-7.5,-10.25,3.1>, <-3.5,-17.5,3.5>, <-3.1,-10.25,7.5> }
		triangle { <-7.5,-10.25,3.1>, <-5,-17.5,0>, <-3.5,-17.5,3.5> }
		triangle { <-5,-17.5,0>, <-7.5,-10.25,3.1>, <-7.5,-10.25,0> }
// lower half right
		triangle { <7.5,-10.25,0>, <4.5,-3.75,0>, <4.5,-3.75,1.9675> }
		triangle { <4.5,-3.75,1.9675>, <7.5,-10.25,3.1>, <7.5,-10.25,0> }
		triangle { <7.5,-10.25,3.1>, <4.5,-3.75,1.9675>, <1.9675,-3.75,4.5> }
		triangle { <1.9675,-3.75,4.5>, <3.1,-10.25,7.5>, <7.5,-10.25,3.1> }
		triangle { <3.1,-10.25,7.5>, <1.9675,-3.75,4.5>, <-1.9675,-3.75,4.5> }
		triangle { <-1.9675,-3.75,4.5>, <-3.1,-10.25,7.5>, <3.1,-10.25,7.5> }
// lower half left
		triangle { <-3.1,-10.25,7.5>, <-1.9675,-3.75,4.5>, <-4.5,-3.75,1.9675> }
		triangle { <-4.5,-3.75,1.9675>, <-7.5,-10.25,3.1>, <-3.1,-10.25,7.5> }
		triangle { <-7.5,-10.25,3.1>, <-4.5,-3.75,1.9675>, <-4.5,-3.75,0> }
		triangle { <-4.5,-3.75,0>, <-7.5,-10.25,0>, <-7.5,-10.25,3.1> }
// bottom right
		triangle { <4.5,-3.75,0>, <4.8708,-3.75,0>, <4.5,-3.75,1.9675> }
		triangle { <1.9675,-3.75,4.5>, <4.5,-3.75,1.9675>, <3.4441,-3.75,3.4441> }
		triangle { <0,-3.75,4.5>, <1.9675,-3.75,4.5>, <0,-3.75,4.8708> }
		triangle { <4.8708,-3.75,0>, <5,-3.25,0>, <4.6195,-3.25,1.9135> }
		triangle { <4.8708,-3.75,0>, <4.6195,-3.25,1.9135>, <4.5,-3.75,1.9675> }
		triangle { <4.5,-3.75,1.9675>, <4.6195,-3.25,1.9135>, <3.5355,-3.25,3.5355> }
		triangle { <4.5,-3.75,1.9675>, <3.5355,-3.25,3.5355>, <3.4441,-3.75,3.4441> }
		triangle { <3.4441,-3.75,3.4441>, <3.5355,-3.25,3.5355>, <1.9135,-3.25,4.6195> }
		triangle { <3.4441,-3.75,3.4441>, <1.9135,-3.25,4.6195>, <1.9675,-3.75,4.5> }
		triangle { <1.9675,-3.75,4.5>, <1.9135,-3.25,4.6195>, <0,-3.25,5> }
		triangle { <1.9675,-3.75,4.5>, <0,-3.25,5>, <0,-3.75,4.8708> }
// bottom left
		triangle { <0,-3.75,4.5>, <0,-3.75,4.8708>, <-1.9675,-3.75,4.5> }
		triangle { <-4.5,-3.75,1.9675>, <-1.9675,-3.75,4.5>, <-3.4441,-3.75,3.4441> }
		triangle { <-4.5,-3.75,0>, <-4.5,-3.75,1.9675>, <-4.8708,-3.75,0> }
		triangle { <0,-3.75,4.8708>, <0,-3.25,5>, <-1.9135,-3.25,4.6195> }
		triangle { <0,-3.75,4.8708>, <-1.9135,-3.25,4.6195>, <-1.9675,-3.75,4.5> }
		triangle { <-1.9675,-3.75,4.5>, <-1.9135,-3.25,4.6195>, <-3.5355,-3.25,3.5355> }
		triangle { <-1.9675,-3.75,4.5>, <-3.5355,-3.25,3.5355>, <-3.4441,-3.75,3.4441> }
		triangle { <-3.4441,-3.75,3.4441>, <-3.5355,-3.25,3.5355>, <-4.6195,-3.25,1.9135> }
		triangle { <-3.4441,-3.75,3.4441>, <-4.6195,-3.25,1.9135>, <-4.5,-3.75,1.9675> }
		triangle { <-4.5,-3.75,1.9675>, <-4.6195,-3.25,1.9135>, <-5,-3.25,0> }
		triangle { <-4.5,-3.75,1.9675>, <-5,-3.25,0>, <-4.8708,-3.75,0> }
	}
	object { _2_dash_4con4_dot_dat matrix <1,0,0,0,3.25,0,0,0,1,0,-3.25,0> }
	object { _2_dash_4disc_dot_dat matrix <4,0,0,0,-1,0,0,0,4,0,0,0> }
}
#end
#end // ifndef (s_slash_93252s01_dot_dat)


//// Part s\93247s02.dat
#ifndef (s_slash_93247s02_dot_dat)
#declare s_slash_93247s02_dot_dat = #if (L3Quality = 0) box { <0,0,0>, <4,3,4> } #else object {
// ~Minifig Sword Khopesh Grip Segment 2
// Name: s\93247s02.dat
// Author: Christian Neumann [Wesley]
// !LDRAW_ORG Subpart UPDATE 2011-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2011-12-29 [PTadmin] Official Update 2011-02
	mesh {
		triangle { <4,3,0>, <3.6956,3,1.5308>, <3.6956,1.5,1.5308> }
		triangle { <3.6956,1.5,1.5308>, <4,0.75,0>, <4,3,0> }
		triangle { <3.6956,3,1.5308>, <2.8284,3,2.8284>, <2.8284,2.25,2.8284> }
		triangle { <2.8284,2.25,2.8284>, <3.6956,1.5,1.5308>, <3.6956,3,1.5308> }
		triangle { <2.8284,3,2.8284>, <1.5308,3,3.6956>, <2.8284,2.25,2.8284> }
// 
		triangle { <2.8284,0.75,2.8284>, <2.8284,0,2.8284>, <3.6956,0,1.5308> }
		triangle { <2.8284,0.75,2.8284>, <1.5308,1.5,3.6956>, <1.5308,0,3.6956> }
		triangle { <1.5308,0,3.6956>, <2.8284,0,2.8284>, <2.8284,0.75,2.8284> }
		triangle { <1.5308,1.5,3.6956>, <0,2.25,4>, <0,0,4> }
		triangle { <0,0,4>, <1.5308,0,3.6956>, <1.5308,1.5,3.6956> }
// 
// 
// 
// 
// upper groove surface
		triangle { <3.23365,0,1.33945>, <2.8284,0.75,2.8284>, <3.6956,0,1.5308> }
		triangle { <2.8284,0.75,2.8284>, <3.23365,0,1.33945>, <2.47485,0.75,2.47485> }
		triangle { <2.8284,0.75,2.8284>, <2.47485,0.75,2.47485>, <1.33945,1.5,3.23365> }
		triangle { <1.33945,1.5,3.23365>, <1.5308,1.5,3.6956>, <2.8284,0.75,2.8284> }
		triangle { <1.5308,1.5,3.6956>, <1.33945,1.5,3.23365>, <0,2.25,3.5> }
		triangle { <0,2.25,4>, <1.5308,1.5,3.6956>, <0,2.25,3.5> }
// lower groove surface
		triangle { <3.6956,1.5,1.5308>, <3.23365,1.5,1.33945>, <3.5,0.75,0> }
		triangle { <4,0.75,0>, <3.6956,1.5,1.5308>, <3.5,0.75,0> }
		triangle { <2.8284,2.25,2.8284>, <2.47485,2.25,2.47485>, <3.23365,1.5,1.33945> }
		triangle { <3.23365,1.5,1.33945>, <3.6956,1.5,1.5308>, <2.8284,2.25,2.8284> }
		triangle { <2.8284,2.25,2.8284>, <1.33945,3,3.23365>, <2.47485,2.25,2.47485> }
		triangle { <1.33945,3,3.23365>, <2.8284,2.25,2.8284>, <1.5308,3,3.6956> }
	}
}
#end
#end // ifndef (s_slash_93247s02_dot_dat)


//// Part s\93247s01.dat
#ifndef (s_slash_93247s01_dot_dat)
#declare s_slash_93247s01_dot_dat = #if (L3Quality = 0) box { <0,0,0>, <4,3,4> } #else object {
// ~Minifig Sword Khopesh Grip Segment 1
// Name: s\93247s01.dat
// Author: Christian Neumann [Wesley]
// !LDRAW_ORG Subpart UPDATE 2011-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2011-12-29 [PTadmin] Official Update 2011-02
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
}
#end
#end // ifndef (s_slash_93247s01_dot_dat)


//// Part s\93247s03.dat
#ifndef (s_slash_93247s03_dot_dat)
#declare s_slash_93247s03_dot_dat = #if (L3Quality = 0) box { <0,0,0>, <4,0.75,4> } #else object {
// ~Minifig Sword Khopesh Grip Endsegment
// Name: s\93247s03.dat
// Author: Christian Neumann [Wesley]
// !LDRAW_ORG Subpart UPDATE 2011-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2011-12-29 [PTadmin] Official Update 2011-02
// outer surface
	mesh {
		triangle { <1.5308,0,3.6956>, <2.8284,0,2.8284>, <2.8284,0.75,2.8284> }
		triangle { <2.8284,0.75,2.8284>, <1.5308,0.75,3.6956>, <1.5308,0,3.6956> }
		triangle { <2.8284,0,2.8284>, <3.6956,0,1.5308>, <3.6956,0.75,1.5308> }
		triangle { <3.6956,0.75,1.5308>, <2.8284,0.75,2.8284>, <2.8284,0,2.8284> }
		triangle { <3.6956,0,1.5308>, <4,0,0>, <4,0.75,0> }
		triangle { <4,0.75,0>, <3.6956,0.75,1.5308>, <3.6956,0,1.5308> }
		triangle { <0,0.75,4>, <1.5308,0,3.6956>, <1.5308,0.75,3.6956> }
// groove end surface
		triangle { <0,0.75,3.5>, <1.33945,0,3.23365>, <0,0.75,4> }
		triangle { <1.5308,0,3.6956>, <0,0.75,4>, <1.33945,0,3.23365> }
	}
}
#end
#end // ifndef (s_slash_93247s03_dot_dat)


//// Part 93252.dat
#ifndef (_93252_dot_dat)
#declare _93252_dot_dat = #if (L3Quality = 0) box { <-7.5,-48,-19>, <7.5,102.503,19> } #else union {
// Minifig Pharaoh's Staff with Forked End
// Name: 93252.dat
// Author: Christian Neumann [Wesley]
// !LDRAW_ORG Part UPDATE 2011-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !CATEGORY Minifig Accessory
// !KEYWORDS Pharaoh's Quest
// !HISTORY 2011-12-29 [PTadmin] Official Update 2011-02
// BFC INVERTNEXT
	object { _4_dash_4cylc_dot_dat matrix <4,0,0,0,-10,0,0,0,4,0,-7.5,0> }
	object { s_slash_93252s01_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
	object { s_slash_93252s01_dot_dat matrix <1,0,0,0,1,0,0,0,-1,0,0,0> }
// socket/shaft edges
// staff
	object { _4_dash_4cyli_dot_dat matrix <3.5,0,0,0,94.458,0,0,0,3.5,0,0,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,0,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,0,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,0,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,0,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,6.228,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,6.228,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,6.228,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,6.228,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,6.228,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,6.228,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,6.228,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,6.228,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,12.456,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,12.456,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,12.456,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,12.456,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,12.456,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,12.456,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,12.456,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,12.456,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,18.684,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,18.684,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,18.684,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,18.684,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,18.684,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,18.684,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,18.684,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,18.684,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,24.912,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,24.912,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,24.912,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,24.912,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,24.912,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,24.912,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,24.912,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,24.912,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,31.14,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,31.14,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,31.14,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,31.14,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,31.14,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,31.14,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,31.14,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,31.14,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,37.368,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,37.368,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,37.368,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,37.368,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,37.368,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,37.368,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,37.368,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,37.368,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,43.596,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,43.596,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,43.596,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,43.596,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,43.596,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,43.596,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,43.596,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,43.596,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,49.824,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,49.824,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,49.824,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,49.824,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,49.824,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,49.824,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,49.824,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,49.824,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,56.052,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,56.052,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,56.052,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,56.052,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,56.052,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,56.052,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,56.052,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,56.052,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,62.28,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,62.28,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,62.28,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,62.28,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,62.28,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,62.28,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,62.28,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,62.28,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,68.508,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,68.508,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,68.508,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,68.508,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,68.508,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,68.508,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,68.508,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,68.508,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,74.736,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,74.736,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,74.736,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,74.736,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,74.736,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,74.736,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,74.736,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,74.736,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,80.964,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,80.964,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,80.964,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,80.964,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,80.964,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,80.964,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,80.964,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,80.964,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,87.192,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,87.192,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,87.192,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,87.192,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,1.038,0,0,0,1,0,87.192,0> }
	object { s_slash_93247s01_dot_dat matrix <1,0,0,0,1.038,0,0,0,-1,0,87.192,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,1.038,0,0,0,-1,0,87.192,0> }
	object { s_slash_93247s01_dot_dat matrix <-1,0,0,0,1.038,0,0,0,1,0,87.192,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,-1.038,0,0,0,1,0,93.42,0> }
	object { s_slash_93247s02_dot_dat matrix <1,0,0,0,-1.038,0,0,0,-1,0,93.42,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,-1,0,93.42,0> }
	object { s_slash_93247s02_dot_dat matrix <-1,0,0,0,-1.038,0,0,0,1,0,93.42,0> }
	object { s_slash_93247s03_dot_dat matrix <0,0,-1,0,1.038,0,1,0,0,0,93.42,0> }
	object { s_slash_93247s03_dot_dat matrix <0,0,-1,0,1.038,0,-1,0,0,0,93.42,0> }
	object { s_slash_93247s03_dot_dat matrix <0,0,1,0,1.038,0,-1,0,0,0,93.42,0> }
	object { s_slash_93247s03_dot_dat matrix <0,0,1,0,1.038,0,1,0,0,0,93.42,0> }
	object { _4_dash_4cyli_dot_dat matrix <4,0,0,0,8.304,0,0,0,4,0,94.1985,0> }
	object { _4_dash_4disc_dot_dat matrix <4,0,0,0,-1.038,0,0,0,4,0,102.503,0> }
}
#end
#end // ifndef (_93252_dot_dat)


//// Model weapon_021_pharaohstaff.ldr
#ifndef (weapon__021__pharaohstaff_dot_ldr)
#declare weapon__021__pharaohstaff_dot_ldr = object {
// Untitled
// Name: weapon_021_pharaohstaff.ldr
// Author: MLCad
// Unofficial Model
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	// 1 4  0 -28 0  0 0 -1  0 1 0  1 0 0 93252.dat
	object {
		_93252_dot_dat
		matrix <1-L3SW/15,0,0,0,1-L3SW/150.503,0,0,0,1-L3SW/38,0,L3SW/5.52277,0>
		matrix <0,0,1,0,1,0,-1,0,0,0,-28,0>
		material { L3Color4 }
	}
}
#end // ifndef (weapon__021__pharaohstaff_dot_ldr)


//// ModelData
#declare L3ModelBBoxMin = <-19,-76,-7.5>;
#declare L3ModelBBoxMax = <19,74.5025,7.5>;
#declare L3ModelBBoxCenter = (L3ModelBBoxMin+L3ModelBBoxMax)/2; // <0,-0.748749,0>
#declare L3ModelBBoxSize = L3ModelBBoxMax-L3ModelBBoxMin; // <38,150.503,15>
#declare L3FloorY = L3ModelBBoxMax.y;

//// ModelObject weapon_021_pharaohstaff.ldr
object { weapon__021__pharaohstaff_dot_ldr }



//// Statistics
//               PARTS             P         Total
// DAT files:        6             7            14
// POV Equivs:       -             3 (43%)
// Model has 2 parts (0 studs)

//// IncludeFile AtEnd
#include "weapons_camera.inc"

//// End
