// Generated by L3P v1.4 BETA 20131202 (Win32)  (C) 1998-2013 Lars C. Hassing SP.lars@AM.hassings.dk
// L3P website:  http://www.hassings.dk/l3/l3p.html
// LDraw.org:    http://www.ldraw.org
// Date:         Fri Aug 22 22:42:08 2014
// Input file:   D:\Datsville RPG\trunk\povray_source\pov_main_project\items\weapon_008_laserpistol.ldr
// Title:        Untitled
// Author:       MLCad
// ModelDir:     D:\Datsville RPG\trunk\povray_source\pov_main_project\items
// WorkDir:      D:\Datsville RPG\trunk\povray_source\pov_main_project\items
// LDRAWDIR:     E:\Programs Windows\LDraw (LDRAWDIR environment variable)
// SearchDirs:   (Default)
// SearchDir1:   D:\Datsville RPG\trunk\povray_source\pov_main_project\items\ (0x10)
// SearchDir2:   E:\Programs Windows\LDraw\P\ (0x9)
// SearchDir3:   E:\Programs Windows\LDraw\PARTS\ (0x4)
// SearchDir4:   E:\Programs Windows\LDraw\MODELS\ (0x0)
// ldconfig.ldr: E:\Programs Windows\LDraw\ldconfig.ldr
// Commandline:  "E:\Programs Windows\l3p14beta\l3p.exe" "D:\Datsville RPG\trunk\povray_source\pov_main_project\items\weapon_008_laserpistol.ldr" "D:\Datsville RPG\trunk\povray_source\pov_main_project\items\weapon_008_laserpistol.pov" -o -ic -il -ibitems.inc -ieweapons_camera.inc

#if (version < 3.1)
	#error "This POV code requires at least version 3.1\n"
#end

//// Defines

#declare L3Version = 1.4;

#declare L3Quality = 2;  // Quality level, 0=BBox, 1=no refr, 2=normal, 3=studlogo, 4=stud2logo

#declare L3SW = 0.5;  // Width of seam between two bricks

#declare L3Studs = 1;  // 1=on 0=off

#declare L3Bumps = 0;  // 1=on 0=off


#declare L3Ambient = 0.4;
#declare L3Diffuse = 0.4;
#declare L3Ior     = 1.25;
#declare L3NormalBumps = normal { bumps 0.01 scale 20 }
#declare L3NormalSlope = normal { bumps 0.3 scale 0.5 }


#declare L3SWT = (L3SW ? L3SW : 0.001);  // At least a small seam when transparent

#declare L3Logo = union {
	sphere {<-59,0,-96>,6}
	cylinder {<-59,0,-96>,<59,0,-122>,6 open}
	sphere {<59,0,-122>,6}
	cylinder {<59,0,-122>,<59,0,-84>,6 open}
	sphere {<59,0,-84>,6}

	sphere {<-59,0,-36>,6}
	cylinder {<-59,0,-36>,<-59,0,1>,6 open}
	sphere {<-59,0,1>,6}
	cylinder {<0,0,-49>,<0,0,-25>,6 open}
	sphere {<0,0,-25>,6}
	sphere {<59,0,-62>,6}
	cylinder {<59,0,-62>,<59,0,-24>,6 open}
	sphere {<59,0,-24>,6}
	cylinder {<-59,0,-36>,<59,0,-62>,6 open}

	sphere {<-35.95,0,57>,6}
	torus {18.45,6 clipped_by{plane{<40,0,-9>,0}} translate<-40,0,39>}
	cylinder {<-44.05,0,21>,<35.95,0,3>,6 open}
	torus {18.45,6 clipped_by{plane{<-40,0,9>,0}} translate<40,0,21>}
	cylinder {<44.05,0,39>,<0,0,49>,6 open}
	sphere {<0,0,49>,6}
	cylinder {<0,0,49>,<0,0,34>,6 open}
	sphere {<0,0,34>,6}

	torus {18.45,6 clipped_by{plane{<40,0,-9>,0}} translate<-40,0,99>}
	cylinder {<-44.05,0,81>,<35.95,0,63>,6 open}
	torus {18.45,6 clipped_by{plane{<-40,0,9>,0}} translate<40,0,81>}
	cylinder {<44.05,0,99>,<-35.95,0,117>,6 open}

	scale 4.5/128
}


//// IncludeFile AtBeginning
#include "items_settings.inc"



//// Finishes
#ifndef (L3FinishOpaque)
#declare L3FinishOpaque = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.5
		phong_size 40
		reflection 0.08
	#end
}
#end

#ifndef (L3FinishChrome)
#declare L3FinishChrome = finish {
	ambient 0.25
	diffuse 0.6
	#if (L3Quality >= 2)
		brilliance 5
		metallic
		specular 0.80
		roughness 1/100
		reflection 0.65
	#end
}
#end

#ifndef (L3FinishPearlescent)
//Not supported yet, using Opaque
#declare L3FinishPearlescent = finish { L3FinishOpaque }
#end

#ifndef (L3FinishRubber)
#declare L3FinishRubber = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.1
		phong_size 10
		reflection 0
	#end
}
#end

#ifndef (L3FinishMatte_metallic)
//Not supported yet, using Opaque
#declare L3FinishMatte_metallic = finish { L3FinishOpaque }
#end

#ifndef (L3FinishMetal)
//Not supported yet, using Opaque
#declare L3FinishMetal = finish { L3FinishOpaque }
#end

#ifndef (L3FinishTransparent)
#declare L3FinishTransparent = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.5
		phong_size 40
		reflection 0.2
	#end
}
#end



//// Macros
#ifndef (L3TextureOpaqueRGB)
#macro L3TextureOpaqueRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishOpaque }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureChromeRGB)
#macro L3TextureChromeRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishChrome }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TexturePearlescentRGB)
#macro L3TexturePearlescentRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishPearlescent }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureRubberRGB)
#macro L3TextureRubberRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishRubber }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureMatte_metallicRGB)
#macro L3TextureMatte_metallicRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishMatte_metallic }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureMetalRGB)
#macro L3TextureMetalRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishMetal }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureTransparentRGBA)
#macro L3TextureTransparentRGBA(r,g,b,a)
// Alpha -> Filter: 255 -> 1.00, 128 -> 0.85, 0 -> 0
#local f = (a >= 128 ? 0.85 + (a-128) * 0.15 / (255-128) : a * 0.85 / 255);
texture {
	pigment { rgb <r/255,g/255,b/255> #if (L3Quality > 1) filter f #end }
	finish { L3FinishTransparent }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureSlope)
#macro L3TextureSlope(tex)
texture {
	tex
	#if (L3Quality > 1) normal { L3NormalSlope } #end
}
#end
#end

#ifndef (L3Material)
#macro L3Material(tex)
material {
	texture { tex }
}
#end
#end

#ifndef (L3MaterialT)
#macro L3MaterialT(tex)
material {
	texture { tex }
	#if (L3Quality > 1)
		interior { ior L3Ior }
	#end
}
#end
#end



//// Color 7 Light_Gray (from ldconfig.ldr)
#ifndef (L3Texture7)
#declare L3Texture7 = L3TextureOpaqueRGB(155,161,157)
#end
#ifndef (L3Texture7_slope)
#declare L3Texture7_slope = L3TextureSlope(L3Texture7)
#end
#ifndef (L3Color7)
#declare L3Color7 = L3Material(L3Texture7)
#end
#ifndef (L3Color7_slope)
#declare L3Color7_slope = L3Material(L3Texture7_slope)
#end


//// Primitive stud2.dat
#ifndef (stud2_dot_dat)
#declare stud2_dot_dat = 
#if (L3Quality >= 4)
union {
#end
	difference {
		cylinder { <0,0,0>, <0,-4,0>, 6 }
		cylinder { <0,1,0>, <0,-5,0>, 4 }
	}
#if (L3Quality >= 4)
	object { L3Logo scale 0.75 }
}
#end
#end // ifndef (stud2_dot_dat)


//// Primitive t01o1429.dat
#ifndef (t01o1429_dot_dat)
#declare t01o1429_dot_dat = object {
// Torus Outside  1 x 0.1429 x 1
// Name: t01o1429.dat
// Author: Santeri Piippo [arezey]
// !LDRAW_ORG Primitive UPDATE 2013-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2010-04-05 [PTadmin] Official Update 2010-01
// !HISTORY 2013-09-27 [MMR1988] Recreated to fix condlines
// !HISTORY 2013-12-23 [PTadmin] Official Update 2013-02
// Major Radius: 7
// Tube(Minor) Radius: 1
// Segments(Sweep): 16/16 = 1.00
// 1  9  0 0 0  1 0 0  0 1 0  0 0 1 4-4edge.dat
// 1  12  1 0 0 0.1429 0 0  0 0 0.1429  0 1 0  4-4edge.dat
	mesh {
		triangle { <1,0.1429,0>, <0.9239,0.1429,0.3827>, <0.9744,0.132,0.4036> }
		triangle { <0.9744,0.132,0.4036>, <1.0547,0.132,0>, <1,0.1429,0> }
		triangle { <1.0547,0.132,0>, <0.9744,0.132,0.4036>, <1.0172,0.101,0.4214> }
		triangle { <1.0172,0.101,0.4214>, <1.101,0.101,0>, <1.0547,0.132,0> }
		triangle { <1.101,0.101,0>, <1.0172,0.101,0.4214>, <1.0458,0.0547,0.4332> }
		triangle { <1.0458,0.0547,0.4332>, <1.132,0.0547,0>, <1.101,0.101,0> }
		triangle { <1.132,0.0547,0>, <1.0458,0.0547,0.4332>, <1.0559,0,0.4374> }
		triangle { <1.0559,0,0.4374>, <1.1429,0,0>, <1.132,0.0547,0> }
		triangle { <0.9239,0.1429,0.3827>, <0.7071,0.1429,0.7071>, <0.7458,0.132,0.7458> }
		triangle { <0.7458,0.132,0.7458>, <0.9744,0.132,0.4036>, <0.9239,0.1429,0.3827> }
		triangle { <0.9744,0.132,0.4036>, <0.7458,0.132,0.7458>, <0.7785,0.101,0.7785> }
		triangle { <0.7785,0.101,0.7785>, <1.0172,0.101,0.4214>, <0.9744,0.132,0.4036> }
		triangle { <1.0172,0.101,0.4214>, <0.7785,0.101,0.7785>, <0.8004,0.0547,0.8004> }
		triangle { <0.8004,0.0547,0.8004>, <1.0458,0.0547,0.4332>, <1.0172,0.101,0.4214> }
		triangle { <1.0458,0.0547,0.4332>, <0.8004,0.0547,0.8004>, <0.8081,0,0.8081> }
		triangle { <0.8081,0,0.8081>, <1.0559,0,0.4374>, <1.0458,0.0547,0.4332> }
		triangle { <0.7071,0.1429,0.7071>, <0.3827,0.1429,0.9239>, <0.4036,0.132,0.9744> }
		triangle { <0.4036,0.132,0.9744>, <0.7458,0.132,0.7458>, <0.7071,0.1429,0.7071> }
		triangle { <0.7458,0.132,0.7458>, <0.4036,0.132,0.9744>, <0.4214,0.101,1.0172> }
		triangle { <0.4214,0.101,1.0172>, <0.7785,0.101,0.7785>, <0.7458,0.132,0.7458> }
		triangle { <0.7785,0.101,0.7785>, <0.4214,0.101,1.0172>, <0.4332,0.0547,1.0458> }
		triangle { <0.4332,0.0547,1.0458>, <0.8004,0.0547,0.8004>, <0.7785,0.101,0.7785> }
		triangle { <0.8004,0.0547,0.8004>, <0.4332,0.0547,1.0458>, <0.4374,0,1.0559> }
		triangle { <0.4374,0,1.0559>, <0.8081,0,0.8081>, <0.8004,0.0547,0.8004> }
		triangle { <0.3827,0.1429,0.9239>, <0,0.1429,1>, <0,0.132,1.0547> }
		triangle { <0,0.132,1.0547>, <0.4036,0.132,0.9744>, <0.3827,0.1429,0.9239> }
		triangle { <0.4036,0.132,0.9744>, <0,0.132,1.0547>, <0,0.101,1.101> }
		triangle { <0,0.101,1.101>, <0.4214,0.101,1.0172>, <0.4036,0.132,0.9744> }
		triangle { <0.4214,0.101,1.0172>, <0,0.101,1.101>, <0,0.0547,1.132> }
		triangle { <0,0.0547,1.132>, <0.4332,0.0547,1.0458>, <0.4214,0.101,1.0172> }
		triangle { <0.4332,0.0547,1.0458>, <0,0.0547,1.132>, <0,0,1.1429> }
		triangle { <0,0,1.1429>, <0.4374,0,1.0559>, <0.4332,0.0547,1.0458> }
		triangle { <0,0.1429,1>, <-0.3827,0.1429,0.9239>, <-0.4036,0.132,0.9744> }
		triangle { <-0.4036,0.132,0.9744>, <0,0.132,1.0547>, <0,0.1429,1> }
		triangle { <0,0.132,1.0547>, <-0.4036,0.132,0.9744>, <-0.4214,0.101,1.0172> }
		triangle { <-0.4214,0.101,1.0172>, <0,0.101,1.101>, <0,0.132,1.0547> }
		triangle { <0,0.101,1.101>, <-0.4214,0.101,1.0172>, <-0.4332,0.0547,1.0458> }
		triangle { <-0.4332,0.0547,1.0458>, <0,0.0547,1.132>, <0,0.101,1.101> }
		triangle { <0,0.0547,1.132>, <-0.4332,0.0547,1.0458>, <-0.4374,0,1.0559> }
		triangle { <-0.4374,0,1.0559>, <0,0,1.1429>, <0,0.0547,1.132> }
		triangle { <-0.3827,0.1429,0.9239>, <-0.7071,0.1429,0.7071>, <-0.7458,0.132,0.7458> }
		triangle { <-0.7458,0.132,0.7458>, <-0.4036,0.132,0.9744>, <-0.3827,0.1429,0.9239> }
		triangle { <-0.4036,0.132,0.9744>, <-0.7458,0.132,0.7458>, <-0.7785,0.101,0.7785> }
		triangle { <-0.7785,0.101,0.7785>, <-0.4214,0.101,1.0172>, <-0.4036,0.132,0.9744> }
		triangle { <-0.4214,0.101,1.0172>, <-0.7785,0.101,0.7785>, <-0.8004,0.0547,0.8004> }
		triangle { <-0.8004,0.0547,0.8004>, <-0.4332,0.0547,1.0458>, <-0.4214,0.101,1.0172> }
		triangle { <-0.4332,0.0547,1.0458>, <-0.8004,0.0547,0.8004>, <-0.8081,0,0.8081> }
		triangle { <-0.8081,0,0.8081>, <-0.4374,0,1.0559>, <-0.4332,0.0547,1.0458> }
		triangle { <-0.7071,0.1429,0.7071>, <-0.9239,0.1429,0.3827>, <-0.9744,0.132,0.4036> }
		triangle { <-0.9744,0.132,0.4036>, <-0.7458,0.132,0.7458>, <-0.7071,0.1429,0.7071> }
		triangle { <-0.7458,0.132,0.7458>, <-0.9744,0.132,0.4036>, <-1.0172,0.101,0.4214> }
		triangle { <-1.0172,0.101,0.4214>, <-0.7785,0.101,0.7785>, <-0.7458,0.132,0.7458> }
		triangle { <-0.7785,0.101,0.7785>, <-1.0172,0.101,0.4214>, <-1.0458,0.0547,0.4332> }
		triangle { <-1.0458,0.0547,0.4332>, <-0.8004,0.0547,0.8004>, <-0.7785,0.101,0.7785> }
		triangle { <-0.8004,0.0547,0.8004>, <-1.0458,0.0547,0.4332>, <-1.0559,0,0.4374> }
		triangle { <-1.0559,0,0.4374>, <-0.8081,0,0.8081>, <-0.8004,0.0547,0.8004> }
		triangle { <-0.9239,0.1429,0.3827>, <-1,0.1429,0>, <-1.0547,0.132,0> }
		triangle { <-1.0547,0.132,0>, <-0.9744,0.132,0.4036>, <-0.9239,0.1429,0.3827> }
		triangle { <-0.9744,0.132,0.4036>, <-1.0547,0.132,0>, <-1.101,0.101,0> }
		triangle { <-1.101,0.101,0>, <-1.0172,0.101,0.4214>, <-0.9744,0.132,0.4036> }
		triangle { <-1.0172,0.101,0.4214>, <-1.101,0.101,0>, <-1.132,0.0547,0> }
		triangle { <-1.132,0.0547,0>, <-1.0458,0.0547,0.4332>, <-1.0172,0.101,0.4214> }
		triangle { <-1.0458,0.0547,0.4332>, <-1.132,0.0547,0>, <-1.1429,0,0> }
		triangle { <-1.1429,0,0>, <-1.0559,0,0.4374>, <-1.0458,0.0547,0.4332> }
		triangle { <-1,0.1429,0>, <-0.9239,0.1429,-0.3827>, <-0.9744,0.132,-0.4036> }
		triangle { <-0.9744,0.132,-0.4036>, <-1.0547,0.132,0>, <-1,0.1429,0> }
		triangle { <-1.0547,0.132,0>, <-0.9744,0.132,-0.4036>, <-1.0172,0.101,-0.4214> }
		triangle { <-1.0172,0.101,-0.4214>, <-1.101,0.101,0>, <-1.0547,0.132,0> }
		triangle { <-1.101,0.101,0>, <-1.0172,0.101,-0.4214>, <-1.0458,0.0547,-0.4332> }
		triangle { <-1.0458,0.0547,-0.4332>, <-1.132,0.0547,0>, <-1.101,0.101,0> }
		triangle { <-1.132,0.0547,0>, <-1.0458,0.0547,-0.4332>, <-1.0559,0,-0.4374> }
		triangle { <-1.0559,0,-0.4374>, <-1.1429,0,0>, <-1.132,0.0547,0> }
		triangle { <-0.9239,0.1429,-0.3827>, <-0.7071,0.1429,-0.7071>, <-0.7458,0.132,-0.7458> }
		triangle { <-0.7458,0.132,-0.7458>, <-0.9744,0.132,-0.4036>, <-0.9239,0.1429,-0.3827> }
		triangle { <-0.9744,0.132,-0.4036>, <-0.7458,0.132,-0.7458>, <-0.7785,0.101,-0.7785> }
		triangle { <-0.7785,0.101,-0.7785>, <-1.0172,0.101,-0.4214>, <-0.9744,0.132,-0.4036> }
		triangle { <-1.0172,0.101,-0.4214>, <-0.7785,0.101,-0.7785>, <-0.8004,0.0547,-0.8004> }
		triangle { <-0.8004,0.0547,-0.8004>, <-1.0458,0.0547,-0.4332>, <-1.0172,0.101,-0.4214> }
		triangle { <-1.0458,0.0547,-0.4332>, <-0.8004,0.0547,-0.8004>, <-0.8081,0,-0.8081> }
		triangle { <-0.8081,0,-0.8081>, <-1.0559,0,-0.4374>, <-1.0458,0.0547,-0.4332> }
		triangle { <-0.7071,0.1429,-0.7071>, <-0.3827,0.1429,-0.9239>, <-0.4036,0.132,-0.9744> }
		triangle { <-0.4036,0.132,-0.9744>, <-0.7458,0.132,-0.7458>, <-0.7071,0.1429,-0.7071> }
		triangle { <-0.7458,0.132,-0.7458>, <-0.4036,0.132,-0.9744>, <-0.4214,0.101,-1.0172> }
		triangle { <-0.4214,0.101,-1.0172>, <-0.7785,0.101,-0.7785>, <-0.7458,0.132,-0.7458> }
		triangle { <-0.7785,0.101,-0.7785>, <-0.4214,0.101,-1.0172>, <-0.4332,0.0547,-1.0458> }
		triangle { <-0.4332,0.0547,-1.0458>, <-0.8004,0.0547,-0.8004>, <-0.7785,0.101,-0.7785> }
		triangle { <-0.8004,0.0547,-0.8004>, <-0.4332,0.0547,-1.0458>, <-0.4374,0,-1.0559> }
		triangle { <-0.4374,0,-1.0559>, <-0.8081,0,-0.8081>, <-0.8004,0.0547,-0.8004> }
		triangle { <-0.3827,0.1429,-0.9239>, <0,0.1429,-1>, <0,0.132,-1.0547> }
		triangle { <0,0.132,-1.0547>, <-0.4036,0.132,-0.9744>, <-0.3827,0.1429,-0.9239> }
		triangle { <-0.4036,0.132,-0.9744>, <0,0.132,-1.0547>, <0,0.101,-1.101> }
		triangle { <0,0.101,-1.101>, <-0.4214,0.101,-1.0172>, <-0.4036,0.132,-0.9744> }
		triangle { <-0.4214,0.101,-1.0172>, <0,0.101,-1.101>, <0,0.0547,-1.132> }
		triangle { <0,0.0547,-1.132>, <-0.4332,0.0547,-1.0458>, <-0.4214,0.101,-1.0172> }
		triangle { <-0.4332,0.0547,-1.0458>, <0,0.0547,-1.132>, <0,0,-1.1429> }
		triangle { <0,0,-1.1429>, <-0.4374,0,-1.0559>, <-0.4332,0.0547,-1.0458> }
		triangle { <0,0.1429,-1>, <0.3827,0.1429,-0.9239>, <0.4036,0.132,-0.9744> }
		triangle { <0.4036,0.132,-0.9744>, <0,0.132,-1.0547>, <0,0.1429,-1> }
		triangle { <0,0.132,-1.0547>, <0.4036,0.132,-0.9744>, <0.4214,0.101,-1.0172> }
		triangle { <0.4214,0.101,-1.0172>, <0,0.101,-1.101>, <0,0.132,-1.0547> }
		triangle { <0,0.101,-1.101>, <0.4214,0.101,-1.0172>, <0.4332,0.0547,-1.0458> }
		triangle { <0.4332,0.0547,-1.0458>, <0,0.0547,-1.132>, <0,0.101,-1.101> }
		triangle { <0,0.0547,-1.132>, <0.4332,0.0547,-1.0458>, <0.4374,0,-1.0559> }
		triangle { <0.4374,0,-1.0559>, <0,0,-1.1429>, <0,0.0547,-1.132> }
		triangle { <0.3827,0.1429,-0.9239>, <0.7071,0.1429,-0.7071>, <0.7458,0.132,-0.7458> }
		triangle { <0.7458,0.132,-0.7458>, <0.4036,0.132,-0.9744>, <0.3827,0.1429,-0.9239> }
		triangle { <0.4036,0.132,-0.9744>, <0.7458,0.132,-0.7458>, <0.7785,0.101,-0.7785> }
		triangle { <0.7785,0.101,-0.7785>, <0.4214,0.101,-1.0172>, <0.4036,0.132,-0.9744> }
		triangle { <0.4214,0.101,-1.0172>, <0.7785,0.101,-0.7785>, <0.8004,0.0547,-0.8004> }
		triangle { <0.8004,0.0547,-0.8004>, <0.4332,0.0547,-1.0458>, <0.4214,0.101,-1.0172> }
		triangle { <0.4332,0.0547,-1.0458>, <0.8004,0.0547,-0.8004>, <0.8081,0,-0.8081> }
		triangle { <0.8081,0,-0.8081>, <0.4374,0,-1.0559>, <0.4332,0.0547,-1.0458> }
		triangle { <0.7071,0.1429,-0.7071>, <0.9239,0.1429,-0.3827>, <0.9744,0.132,-0.4036> }
		triangle { <0.9744,0.132,-0.4036>, <0.7458,0.132,-0.7458>, <0.7071,0.1429,-0.7071> }
		triangle { <0.7458,0.132,-0.7458>, <0.9744,0.132,-0.4036>, <1.0172,0.101,-0.4214> }
		triangle { <1.0172,0.101,-0.4214>, <0.7785,0.101,-0.7785>, <0.7458,0.132,-0.7458> }
		triangle { <0.7785,0.101,-0.7785>, <1.0172,0.101,-0.4214>, <1.0458,0.0547,-0.4332> }
		triangle { <1.0458,0.0547,-0.4332>, <0.8004,0.0547,-0.8004>, <0.7785,0.101,-0.7785> }
		triangle { <0.8004,0.0547,-0.8004>, <1.0458,0.0547,-0.4332>, <1.0559,0,-0.4374> }
		triangle { <1.0559,0,-0.4374>, <0.8081,0,-0.8081>, <0.8004,0.0547,-0.8004> }
		triangle { <0.9239,0.1429,-0.3827>, <1,0.1429,0>, <1.0547,0.132,0> }
		triangle { <1.0547,0.132,0>, <0.9744,0.132,-0.4036>, <0.9239,0.1429,-0.3827> }
		triangle { <0.9744,0.132,-0.4036>, <1.0547,0.132,0>, <1.101,0.101,0> }
		triangle { <1.101,0.101,0>, <1.0172,0.101,-0.4214>, <0.9744,0.132,-0.4036> }
		triangle { <1.0172,0.101,-0.4214>, <1.101,0.101,0>, <1.132,0.0547,0> }
		triangle { <1.132,0.0547,0>, <1.0458,0.0547,-0.4332>, <1.0172,0.101,-0.4214> }
		triangle { <1.0458,0.0547,-0.4332>, <1.132,0.0547,0>, <1.1429,0,0> }
		triangle { <1.1429,0,0>, <1.0559,0,-0.4374>, <1.0458,0.0547,-0.4332> }
// conditional lines
// Build by Primitive Generator 2
	}
}
#end // ifndef (t01o1429_dot_dat)


//// Primitive 4-4disc.dat
#ifndef (_4_dash_4disc_dot_dat)
#declare _4_dash_4disc_dot_dat = disc { <0,0,0>, <0,1,0>, 1 }
#end // ifndef (_4_dash_4disc_dot_dat)


//// Primitive 4-4cyli.dat
#ifndef (_4_dash_4cyli_dot_dat)
#declare _4_dash_4cyli_dot_dat = cylinder { <0,0,0>, <0,1,0>, 1 open }
#end // ifndef (_4_dash_4cyli_dot_dat)


//// Primitive 4-4cylo.dat
#ifndef (_4_dash_4cylo_dot_dat)
#declare _4_dash_4cylo_dot_dat = object {
// Cylinder Open 1.0
// Name: 4-4cylo.dat
// Author: Mark Kennedy [mkennedy]
// !LDRAW_ORG Primitive UPDATE 2010-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2010-04-05 [PTadmin] Official Update 2010-01
	object { _4_dash_4cyli_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
}
#end // ifndef (_4_dash_4cylo_dot_dat)


//// Primitive 4-4con13.dat
#ifndef (_4_dash_4con13_dot_dat)
#declare _4_dash_4con13_dot_dat = cone { <0,0,0>, 14, <0,1,0>, 13 open }
#end // ifndef (_4_dash_4con13_dot_dat)


//// Primitive 4-4con24.dat
#ifndef (_4_dash_4con24_dot_dat)
#declare _4_dash_4con24_dot_dat = cone { <0,0,0>, 25, <0,1,0>, 24 open }
#end // ifndef (_4_dash_4con24_dot_dat)


//// Primitive 3-16chrd.dat
#ifndef (_3_dash_16chrd_dot_dat)
#declare _3_dash_16chrd_dot_dat = object {
// Chord 0.1875
// Name: 3-16chrd.dat
// Author: Niels Karsdorp [nielsk]
// !LDRAW_ORG Primitive UPDATE 2009-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2009-05-02 [PTadmin] Official Update 2009-01
	mesh {
		triangle { <1,0,0>, <0.9239,0,0.3827>, <0.7071,0,0.7071> }
		triangle { <0.7071,0,0.7071>, <0.3827,0,0.9239>, <1,0,0> }
	}
}
#end // ifndef (_3_dash_16chrd_dot_dat)


//// Primitive 1-4chrd.dat
#ifndef (_1_dash_4chrd_dot_dat)
#declare _1_dash_4chrd_dot_dat = disc { <0,0,0>, <0,1,0>, 1 clipped_by { plane { <-1,0,-1>, -sqrt(1/2) } } }
#end // ifndef (_1_dash_4chrd_dot_dat)


//// Primitive 2-4disc.dat
#ifndef (_2_dash_4disc_dot_dat)
#declare _2_dash_4disc_dot_dat = disc { <0,0,0>, <0,1,0>, 1 clipped_by { box { <-2,-1,0>, <2,1,2> } } }
#end // ifndef (_2_dash_4disc_dot_dat)


//// Primitive 2-4cyli.dat
#ifndef (_2_dash_4cyli_dot_dat)
#declare _2_dash_4cyli_dot_dat = cylinder { <0,0,0>, <0,1,0>, 1 open clipped_by { plane { -z, 0 } } }
#end // ifndef (_2_dash_4cyli_dot_dat)


//// Primitive 2-4cylc.dat
#ifndef (_2_dash_4cylc_dot_dat)
#declare _2_dash_4cylc_dot_dat = union {
// Cylinder Closed 0.5
// Name: 2-4cylc.dat
// Author: Alex Taylor [anathema]
// !LDRAW_ORG Primitive UPDATE 2009-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2009-09-03 [PTadmin] Official Update 2009-02
	object { _2_dash_4disc_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
	object { _2_dash_4cyli_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
}
#end // ifndef (_2_dash_4cylc_dot_dat)


//// Primitive 2-4ndis.dat
#ifndef (_2_dash_4ndis_dot_dat)
#declare _2_dash_4ndis_dot_dat = disc { <0,0,0>, <0,1,0>, 2, 1 clipped_by { box { <-1,-1,0>, <1,1,1> } } }
#end // ifndef (_2_dash_4ndis_dot_dat)


//// Primitive box3u8p.dat
#ifndef (box3u8p_dot_dat)
#declare box3u8p_dot_dat = object {
// Box with 3 Faces and 4 Parallel Edges
// Name: box3u8p.dat
// Author: James Jessiman
// !LDRAW_ORG Primitive UPDATE 2012-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2002-12-13 [hafhead] Made BFC compliant
// !HISTORY 2003-08-01 [PTadmin] Official Update 2003-02
// !HISTORY 2007-06-24 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2012-02-16 [Philo] Changed to CCW
// !HISTORY 2012-03-30 [PTadmin] Official Update 2012-01
	mesh {
		triangle { <1,1,-1>, <-1,1,-1>, <-1,1,1> }
		triangle { <-1,1,1>, <1,1,1>, <1,1,-1> }
		triangle { <-1,1,1>, <-1,0,1>, <1,0,1> }
		triangle { <1,0,1>, <1,1,1>, <-1,1,1> }
		triangle { <1,1,-1>, <1,0,-1>, <-1,0,-1> }
		triangle { <-1,0,-1>, <-1,1,-1>, <1,1,-1> }
	}
}
#end // ifndef (box3u8p_dot_dat)


//// Primitive 2-4con19.dat
#ifndef (_2_dash_4con19_dot_dat)
#declare _2_dash_4con19_dot_dat = object {
// Cone 19 x 0.5
// Name: 2-4con19.dat
// Author: Michael Heidemann [mikeheide]
// !LDRAW_ORG Primitive UPDATE 2010-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2010-07-05 [PTadmin] Official Update 2010-02
	mesh {
		triangle { <19,1,0>, <17.5541,1,7.2713>, <18.478,0,7.654> }
		triangle { <18.478,0,7.654>, <20,0,0>, <19,1,0> }
		triangle { <17.5541,1,7.2713>, <13.4349,1,13.4349>, <14.142,0,14.142> }
		triangle { <14.142,0,14.142>, <18.478,0,7.654>, <17.5541,1,7.2713> }
		triangle { <13.4349,1,13.4349>, <7.2713,1,17.5541>, <7.654,0,18.478> }
		triangle { <7.654,0,18.478>, <14.142,0,14.142>, <13.4349,1,13.4349> }
		triangle { <7.2713,1,17.5541>, <0,1,19>, <0,0,20> }
		triangle { <0,0,20>, <7.654,0,18.478>, <7.2713,1,17.5541> }
		triangle { <0,1,19>, <-7.2713,1,17.5541>, <-7.654,0,18.478> }
		triangle { <-7.654,0,18.478>, <0,0,20>, <0,1,19> }
		triangle { <-7.2713,1,17.5541>, <-13.4349,1,13.4349>, <-14.142,0,14.142> }
		triangle { <-14.142,0,14.142>, <-7.654,0,18.478>, <-7.2713,1,17.5541> }
		triangle { <-13.4349,1,13.4349>, <-17.5541,1,7.2713>, <-18.478,0,7.654> }
		triangle { <-18.478,0,7.654>, <-14.142,0,14.142>, <-13.4349,1,13.4349> }
		triangle { <-17.5541,1,7.2713>, <-19,1,0>, <-20,0,0> }
		triangle { <-20,0,0>, <-18.478,0,7.654>, <-17.5541,1,7.2713> }
// conditional lines
// end of file
	}
}
#end // ifndef (_2_dash_4con19_dot_dat)


//// Primitive 1-4con5.dat
#ifndef (_1_dash_4con5_dot_dat)
#declare _1_dash_4con5_dot_dat = cone {
	<0,0,0>, 6, <0,1,0>, 5 open
	clipped_by { plane { -x, 0 } plane { -z, 0 } }
}
#end // ifndef (_1_dash_4con5_dot_dat)


//// Part 87993.dat
#ifndef (_87993_dot_dat)
#declare _87993_dot_dat = #if (L3Quality = 0) box { <-9,-29.2124,-29.1354>, <9,9,14.1722> } #else union {
// Minifig Gun Laser Pistol
// Name: 87993.dat
// Author: Philippe Hurbain [Philo]
// !LDRAW_ORG Part UPDATE 2011-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// !HELP Grip-barrel angle = 18 degrees
// BFC CERTIFY CCW
// !CATEGORY Minifig Accessory
// !HISTORY 2011-07-25 [PTadmin] Official Update 2011-01
	#if (L3Studs)
		object { stud2_dot_dat matrix <0,0.95106,-0.30902,0,0.30902,0.95106,1,0,0,0,-22.147,-23.477> }
		object { stud2_dot_dat matrix <0,0.95106,-0.30902,1,0,0,0,-0.30902,-0.95106,-5,-15.967,-4.456> }
		object { stud2_dot_dat matrix <0,0.95106,-0.30902,-1,0,0,0,0.30902,0.95106,5,-15.967,-4.456> }
	#end
	object { t01o1429_dot_dat matrix <0,-6.18187,2.00861,0,-2.16312,-6.6574,6.5,0,0,0,-21.838,-22.526> }
	object { _4_dash_4disc_dot_dat matrix <0,-6.18187,2.00861,0,-0.30902,-0.95106,6.5,0,0,0,-21.529,-21.575> }
	object { _4_dash_4disc_dot_dat matrix <0,6.18187,-2.00861,0,0.30902,0.95106,6.5,0,0,0,-22.147,-23.477> }
	object { t01o1429_dot_dat matrix <0,6.18187,-2.00861,0,2.16312,6.6574,6.5,0,0,0,-21.838,-22.526> }
	object { _4_dash_4cylo_dot_dat matrix <0,3.80423,-1.23607,0,-0.61803,-1.90211,4,0,0,0,-20.911,-19.673> }
	object { _4_dash_4con13_dot_dat matrix <0,0.53406,-0.17353,0,-0.61803,-1.90211,0.56154,0,0,0,-20.293,-17.771> }
	object { _4_dash_4disc_dot_dat matrix <0,-7.47676,2.42935,0,-0.30902,-0.95106,7.86153,0,0,0,-20.293,-17.771> }
	object { _4_dash_4disc_dot_dat matrix <0,-6.94272,2.25582,0,0.30902,0.95106,7.3,0,0,0,-20.911,-19.673> }
	object { _4_dash_4cylo_dot_dat matrix <0,3.80423,-1.23607,0,-0.61803,-1.90211,4,0,0,0,-19.675,-15.869> }
	object { _4_dash_4con24_dot_dat matrix <0,0.33287,-0.10816,0,-0.61803,-1.90211,0.35,0,0,0,-19.057,-13.966> }
	object { _4_dash_4disc_dot_dat matrix <0,-7.98888,2.59574,0,0.30902,0.95106,8.4,0,0,0,-19.675,-15.869> }
	object { _4_dash_4disc_dot_dat matrix <0,-8.32175,2.7039,0,-0.30902,-0.95106,8.75,0,0,0,-19.057,-13.966> }
	object { _4_dash_4cyli_dot_dat matrix <0,3.80423,-1.23607,0,0.55623,1.7119,4,0,0,0,-19.057,-13.966> }
	object { _3_dash_16chrd_dot_dat matrix <0,7.15274,-2.32406,1,0,0,0,5.0151,15.4349,-5,-17.203,-8.26> }
	object { _3_dash_16chrd_dot_dat matrix <0,-7.15274,2.32406,1,0,0,0,5.0151,15.4349,-5,-17.203,-8.26> }
	object { _3_dash_16chrd_dot_dat matrix <0,7.15274,-2.32406,-1,0,0,0,5.0151,15.4349,5,-17.203,-8.26> }
	object { _3_dash_16chrd_dot_dat matrix <0,-7.15274,2.32406,-1,0,0,0,5.0151,15.4349,5,-17.203,-8.26> }
	object { _1_dash_4chrd_dot_dat matrix <0,6.07747,-4.91878,1,0,0,0,-7.80796,-0.40714,-5,-17.326,-8.641> }
	mesh {
		triangle { <-5,-24.356,-5.936>, <-5,-10.05,-10.584>, <-5,-11.249,-13.559> }
		triangle { <-5,-11.249,-13.559>, <-5,-25.134,-9.048>, <-5,-24.356,-5.936> }
		triangle { <-5,-16.395,1.992>, <-5,-11.83,0.509>, <-5,-10.05,-10.584> }
		triangle { <-5,-10.05,-10.584>, <-5,-24.356,-5.936>, <-5,-16.395,1.992> }
		triangle { <-5,-12.948,6.129>, <-5,-12.187,5.882>, <-5,-13.732,1.127> }
		triangle { <-5,-13.732,1.127>, <-5,-14.493,1.374>, <-5,-12.948,6.129> }
// BFC INVERTNEXT
	}
	object { _2_dash_4cylc_dot_dat matrix <0,-0.95106,0.30902,-2,0,0,0,-0.30902,-0.95106,-3,-15.135,2.634> }
	object { _2_dash_4ndis_dot_dat matrix <0,-0.95106,0.30902,1,0,0,0,-0.30902,-0.95106,-5,-15.135,2.634> }
// BFC INVERTNEXT
	object { _2_dash_4cylc_dot_dat matrix <0,0.95106,-0.30902,-2,0,0,0,0.30902,0.95106,-3,-14.208,5.487> }
	object { _2_dash_4ndis_dot_dat matrix <0,0.95106,-0.30902,1,0,0,0,0.30902,0.95106,-5,-14.208,5.487> }
// BFC INVERTNEXT
	object { box3u8p_dot_dat matrix <0,-0.46353,-1.42659,2,0,0,0,-0.95106,0.30902,-5,-14.671,4.061> }
// BFC INVERTNEXT
	object { _2_dash_4cylc_dot_dat matrix <0,0.95106,-0.30902,-2,0,0,0,-0.30902,-0.95106,-3,-12.472,1.769> }
	object { _2_dash_4ndis_dot_dat matrix <0,0.95106,-0.30902,1,0,0,0,-0.30902,-0.95106,-5,-12.472,1.769> }
// BFC INVERTNEXT
	object { _2_dash_4cylc_dot_dat matrix <0,-0.95106,0.30902,-2,0,0,0,0.30902,0.95106,-3,-11.545,4.622> }
	object { _2_dash_4ndis_dot_dat matrix <0,-0.95106,0.30902,1,0,0,0,0.30902,0.95106,-5,-11.545,4.622> }
// BFC INVERTNEXT
	object { box3u8p_dot_dat matrix <0,-0.46353,-1.42659,2,0,0,0,0.95106,-0.30902,-5,-12.009,3.196> }
	mesh {
		triangle { <-5,-24.356,-5.936>, <-5,-15.307,6.889>, <-5,-14.85,6.747> }
		triangle { <-5,-14.85,6.747>, <-5,-16.395,1.992>, <-5,-24.356,-5.936> }
		triangle { <-5,-12.188,7.175>, <-5,-14.85,6.747>, <-5,-15.307,6.889> }
		triangle { <-5,-10.285,5.264>, <-5,-14.85,6.747>, <-5,-12.188,7.175> }
		triangle { <-5,-11.83,0.509>, <-5,-10.285,5.264>, <-5,-9.832,5.111> }
		triangle { <-5,-9.832,5.111>, <-5,-10.05,-10.584>, <-5,-11.83,0.509> }
		triangle { <-5,-9.832,5.111>, <-5,-10.285,5.264>, <-5,-12.188,7.175> }
	}
	object { _1_dash_4chrd_dot_dat matrix <0,6.07747,-4.91878,-1,0,0,0,-7.80796,-0.40714,5,-17.326,-8.641> }
	mesh {
		triangle { <5,-25.134,-9.048>, <5,-11.249,-13.559>, <5,-10.05,-10.584> }
		triangle { <5,-10.05,-10.584>, <5,-24.356,-5.936>, <5,-25.134,-9.048> }
		triangle { <5,-24.356,-5.936>, <5,-10.05,-10.584>, <5,-11.83,0.509> }
		triangle { <5,-11.83,0.509>, <5,-16.395,1.992>, <5,-24.356,-5.936> }
		triangle { <5,-14.493,1.374>, <5,-13.732,1.127>, <5,-12.187,5.882> }
		triangle { <5,-12.187,5.882>, <5,-12.948,6.129>, <5,-14.493,1.374> }
// BFC INVERTNEXT
	}
	object { _2_dash_4cylc_dot_dat matrix <0,-0.95106,0.30902,2,0,0,0,-0.30902,-0.95106,3,-15.135,2.634> }
	object { _2_dash_4ndis_dot_dat matrix <0,-0.95106,0.30902,-1,0,0,0,-0.30902,-0.95106,5,-15.135,2.634> }
// BFC INVERTNEXT
	object { _2_dash_4cylc_dot_dat matrix <0,0.95106,-0.30902,2,0,0,0,0.30902,0.95106,3,-14.208,5.487> }
	object { _2_dash_4ndis_dot_dat matrix <0,0.95106,-0.30902,-1,0,0,0,0.30902,0.95106,5,-14.208,5.487> }
// BFC INVERTNEXT
	object { box3u8p_dot_dat matrix <0,-0.46353,-1.42659,-2,0,0,0,-0.95106,0.30902,5,-14.671,4.061> }
// BFC INVERTNEXT
	object { _2_dash_4cylc_dot_dat matrix <0,0.95106,-0.30902,2,0,0,0,-0.30902,-0.95106,3,-12.472,1.769> }
	object { _2_dash_4ndis_dot_dat matrix <0,0.95106,-0.30902,-1,0,0,0,-0.30902,-0.95106,5,-12.472,1.769> }
// BFC INVERTNEXT
	object { _2_dash_4cylc_dot_dat matrix <0,-0.95106,0.30902,2,0,0,0,0.30902,0.95106,3,-11.545,4.622> }
	object { _2_dash_4ndis_dot_dat matrix <0,-0.95106,0.30902,-1,0,0,0,0.30902,0.95106,5,-11.545,4.622> }
// BFC INVERTNEXT
	object { box3u8p_dot_dat matrix <0,-0.46353,-1.42659,-2,0,0,0,0.95106,-0.30902,5,-12.009,3.196> }
	mesh {
		triangle { <5,-16.395,1.992>, <5,-14.85,6.747>, <5,-15.307,6.889> }
		triangle { <5,-15.307,6.889>, <5,-24.356,-5.936>, <5,-16.395,1.992> }
		triangle { <5,-15.307,6.889>, <5,-14.85,6.747>, <5,-12.188,7.175> }
		triangle { <5,-12.188,7.175>, <5,-14.85,6.747>, <5,-10.285,5.264> }
		triangle { <5,-10.05,-10.584>, <5,-9.832,5.111>, <5,-10.285,5.264> }
		triangle { <5,-10.285,5.264>, <5,-11.83,0.509>, <5,-10.05,-10.584> }
		triangle { <5,-12.188,7.175>, <5,-10.285,5.264>, <5,-9.832,5.111> }
		triangle { <-2.5,-25.786,-5.471>, <-5,-24.356,-5.936>, <-5,-25.134,-9.048> }
		triangle { <-2.5,-26.417,-8.789>, <-2.5,-25.786,-5.471>, <-5,-25.134,-9.048> }
		triangle { <0,-26.238,-5.324>, <-2.5,-25.786,-5.471>, <-2.5,-26.417,-8.789> }
		triangle { <0,-27.003,-8.651>, <0,-26.238,-5.324>, <-2.5,-26.417,-8.789> }
		triangle { <5,-25.134,-9.048>, <5,-24.356,-5.936>, <2.5,-25.786,-5.471> }
		triangle { <5,-25.134,-9.048>, <2.5,-25.786,-5.471>, <2.5,-26.417,-8.789> }
		triangle { <2.5,-26.417,-8.789>, <2.5,-25.786,-5.471>, <0,-26.238,-5.324> }
		triangle { <2.5,-26.417,-8.789>, <0,-26.238,-5.324>, <0,-27.003,-8.651> }
		triangle { <-5,-11.249,-13.559>, <-5,-10.05,-10.584>, <-2.5,-8.619,-11.049> }
		triangle { <-5,-11.249,-13.559>, <-2.5,-8.619,-11.049>, <-2.5,-10.059,-14.104> }
		triangle { <-2.5,-10.059,-14.104>, <-2.5,-8.619,-11.049>, <0,-8.168,-11.196> }
		triangle { <-2.5,-10.059,-14.104>, <0,-8.168,-11.196>, <0,-9.504,-14.337> }
		triangle { <2.5,-8.619,-11.049>, <5,-10.05,-10.584>, <5,-11.249,-13.559> }
		triangle { <2.5,-10.059,-14.104>, <2.5,-8.619,-11.049>, <5,-11.249,-13.559> }
		triangle { <0,-8.168,-11.196>, <2.5,-8.619,-11.049>, <2.5,-10.059,-14.104> }
		triangle { <0,-9.504,-14.337>, <0,-8.168,-11.196>, <2.5,-10.059,-14.104> }
	}
	object { _2_dash_4con19_dot_dat matrix <0,-0.45175,0.14678,-2.5,0,0,0,0.31674,0.97483,0,-17.203,-8.26> }
	object { _1_dash_4con5_dot_dat matrix <0,-1.43055,0.46481,-2.5,0,0,0,1.00302,3.08697,-2.5,-17.203,-8.26> }
	object { _1_dash_4con5_dot_dat matrix <0,1.43055,-0.46481,-2.5,0,0,0,1.00302,3.08697,-2.5,-17.203,-8.26> }
	object { _2_dash_4con19_dot_dat matrix <0,-0.45175,0.14678,2.5,0,0,0,0.31674,0.97483,0,-17.203,-8.26> }
	object { _1_dash_4con5_dot_dat matrix <0,-1.43055,0.46481,2.5,0,0,0,1.00302,3.08697,2.5,-17.203,-8.26> }
	object { _1_dash_4con5_dot_dat matrix <0,1.43055,-0.46481,2.5,0,0,0,1.00302,3.08697,2.5,-17.203,-8.26> }
	mesh {
		triangle { <-5,-11.249,-13.559>, <-2.5,-13.731,-13.961>, <-5,-14.699,-13.34> }
		triangle { <-5,-11.249,-13.559>, <-2.5,-10.059,-14.104>, <-2.5,-13.731,-13.961> }
		triangle { <-2.5,-10.059,-14.104>, <0,-13.277,-14.229>, <-2.5,-13.731,-13.961> }
		triangle { <-2.5,-10.059,-14.104>, <0,-9.504,-14.337>, <0,-13.277,-14.229> }
		triangle { <2.5,-10.059,-14.104>, <5,-14.699,-13.34>, <2.5,-13.731,-13.961> }
		triangle { <2.5,-10.059,-14.104>, <5,-11.249,-13.559>, <5,-14.699,-13.34> }
		triangle { <0,-9.504,-14.337>, <2.5,-13.731,-13.961>, <0,-13.277,-14.229> }
		triangle { <0,-9.504,-14.337>, <2.5,-10.059,-14.104>, <2.5,-13.731,-13.961> }
		triangle { <-5,-14.699,-13.34>, <-2.5,-18.695,-12.852>, <-5,-18.55,-12.407> }
		triangle { <-5,-14.699,-13.34>, <-2.5,-13.731,-13.961>, <-2.5,-18.695,-12.852> }
		triangle { <-2.5,-13.731,-13.961>, <0,-13.277,-14.229>, <0,-18.756,-13.039> }
		triangle { <0,-18.756,-13.039>, <-2.5,-18.695,-12.852>, <-2.5,-13.731,-13.961> }
		triangle { <2.5,-13.731,-13.961>, <5,-18.55,-12.407>, <2.5,-18.695,-12.852> }
		triangle { <2.5,-13.731,-13.961>, <5,-14.699,-13.34>, <5,-18.55,-12.407> }
		triangle { <0,-13.277,-14.229>, <2.5,-13.731,-13.961>, <2.5,-18.695,-12.852> }
		triangle { <2.5,-18.695,-12.852>, <0,-18.756,-13.039>, <0,-13.277,-14.229> }
		triangle { <-5,-18.55,-12.407>, <-2.5,-23.363,-10.831>, <-5,-22.214,-10.899> }
		triangle { <-5,-18.55,-12.407>, <-2.5,-18.695,-12.852>, <-2.5,-23.363,-10.831> }
		triangle { <-2.5,-18.695,-12.852>, <0,-18.756,-13.039>, <0,-23.887,-10.782> }
		triangle { <0,-23.887,-10.782>, <-2.5,-23.363,-10.831>, <-2.5,-18.695,-12.852> }
		triangle { <2.5,-18.695,-12.852>, <5,-22.214,-10.899>, <2.5,-23.363,-10.831> }
		triangle { <2.5,-18.695,-12.852>, <5,-18.55,-12.407>, <5,-22.214,-10.899> }
		triangle { <0,-18.756,-13.039>, <2.5,-18.695,-12.852>, <2.5,-23.363,-10.831> }
		triangle { <2.5,-23.363,-10.831>, <0,-23.887,-10.782>, <0,-18.756,-13.039> }
		triangle { <-5,-22.214,-10.899>, <-2.5,-26.417,-8.789>, <-5,-25.134,-9.048> }
		triangle { <-5,-22.214,-10.899>, <-2.5,-23.363,-10.831>, <-2.5,-26.417,-8.789> }
		triangle { <-2.5,-23.363,-10.831>, <0,-27.003,-8.651>, <-2.5,-26.417,-8.789> }
		triangle { <-2.5,-23.363,-10.831>, <0,-23.887,-10.782>, <0,-27.003,-8.651> }
		triangle { <2.5,-23.363,-10.831>, <5,-25.134,-9.048>, <2.5,-26.417,-8.789> }
		triangle { <2.5,-23.363,-10.831>, <5,-22.214,-10.899>, <5,-25.134,-9.048> }
		triangle { <0,-23.887,-10.782>, <2.5,-26.417,-8.789>, <0,-27.003,-8.651> }
		triangle { <0,-23.887,-10.782>, <2.5,-23.363,-10.831>, <2.5,-26.417,-8.789> }
	}
	object { _4_dash_4disc_dot_dat matrix <0,0,-4.00001,0,-13.7533,9.99237,4,0,0,0,9,0> }
	object { _4_dash_4cyli_dot_dat matrix <0,0,-4.00001,0,17,0,4,0,0,0,-8,0> }
	mesh {
		triangle { <-1.5,-23.087,4.176>, <-1.5,-22.303,2.523>, <-1.5,-22.948,1.608> }
		triangle { <-1.5,-22.948,1.608>, <-1.5,-23.128,1.191>, <-1.5,-23.087,4.176> }
		triangle { <-1.5,-20.749,4.725>, <-1.5,-22.303,2.523>, <-1.5,-23.087,4.176> }
		triangle { <-1.5,-23.087,4.176>, <-1.5,-22.794,7.791>, <-1.5,-20.749,4.725> }
		triangle { <-1.5,-19.201,6.919>, <-1.5,-20.749,4.725>, <-1.5,-22.794,7.791> }
		triangle { <-1.5,-22.794,7.791>, <-1.5,-22.037,9.622>, <-1.5,-19.201,6.919> }
		triangle { <-1.5,-19.201,6.919>, <-1.5,-22.037,9.622>, <-1.5,-20.379,9.85> }
		triangle { <-1.5,-20.379,9.85>, <-1.5,-19.055,7.126>, <-1.5,-19.201,6.919> }
		triangle { <-1.5,-20.379,9.85>, <-1.5,-17.099,8.614>, <-1.5,-19.055,7.126> }
		triangle { <-1.5,-20.379,9.85>, <-1.5,-18.265,9.539>, <-1.5,-16.425,9.127> }
		triangle { <-1.5,-16.425,9.127>, <-1.5,-17.099,8.614>, <-1.5,-20.379,9.85> }
		triangle { <-1.5,-1.784,-3.405>, <-1.5,-1.758,-5.524>, <-1.5,-7.108,-5.221> }
		triangle { <-1.5,-7.108,-5.221>, <-1.5,-6.754,-3.654>, <-1.5,-1.784,-3.405> }
		triangle { <-1.5,-6.754,-3.654>, <-1.5,-6.75,-3.388>, <-1.5,-1.784,-3.405> }
		triangle { <-1.5,-7.656,-7.648>, <-1.5,-7.108,-5.221>, <-1.5,-1.758,-5.524> }
		triangle { <-1.5,-1.758,-5.524>, <-1.5,-2.267,-8.576>, <-1.5,-7.656,-7.648> }
		triangle { <-1.5,-2.267,-8.576>, <-1.5,-3.655,-10.267>, <-1.5,-8.083,-9.533> }
		triangle { <-1.5,-8.083,-9.533>, <-1.5,-7.656,-7.648>, <-1.5,-2.267,-8.576> }
		triangle { <-1.5,-8.089,-9.563>, <-1.5,-8.083,-9.533>, <-1.5,-3.655,-10.267> }
		triangle { <-1.5,-3.655,-10.267>, <-1.5,-5.609,-10.403>, <-1.5,-8.089,-9.563> }
		triangle { <-1.5,-16.425,9.127>, <-1.5,-18.265,9.539>, <1.5,-18.265,9.539> }
		triangle { <1.5,-18.265,9.539>, <1.5,-16.425,9.127>, <-1.5,-16.425,9.127> }
		triangle { <-1.5,-18.265,9.539>, <-1.5,-20.379,9.85>, <1.5,-20.379,9.85> }
		triangle { <1.5,-20.379,9.85>, <1.5,-18.265,9.539>, <-1.5,-18.265,9.539> }
		triangle { <-1.5,-20.379,9.85>, <-1.5,-22.037,9.622>, <1.5,-22.037,9.622> }
		triangle { <1.5,-22.037,9.622>, <1.5,-20.379,9.85>, <-1.5,-20.379,9.85> }
		triangle { <-1.5,-22.037,9.622>, <-1.5,-22.794,7.791>, <1.5,-22.794,7.791> }
		triangle { <1.5,-22.794,7.791>, <1.5,-22.037,9.622>, <-1.5,-22.037,9.622> }
		triangle { <-1.5,-22.794,7.791>, <-1.5,-23.087,4.176>, <1.5,-23.087,4.176> }
		triangle { <1.5,-23.087,4.176>, <1.5,-22.794,7.791>, <-1.5,-22.794,7.791> }
		triangle { <-1.5,-23.087,4.176>, <-1.5,-23.128,1.191>, <1.5,-23.128,1.191> }
		triangle { <1.5,-23.128,1.191>, <1.5,-23.087,4.176>, <-1.5,-23.087,4.176> }
		triangle { <-1.5,-8.089,-9.563>, <-1.5,-5.609,-10.403>, <1.5,-5.609,-10.403> }
		triangle { <1.5,-5.609,-10.403>, <1.5,-8.089,-9.563>, <-1.5,-8.089,-9.563> }
		triangle { <-1.5,-5.609,-10.403>, <-1.5,-3.655,-10.267>, <1.5,-3.655,-10.267> }
		triangle { <1.5,-3.655,-10.267>, <1.5,-5.609,-10.403>, <-1.5,-5.609,-10.403> }
		triangle { <-1.5,-3.655,-10.267>, <-1.5,-2.267,-8.576>, <1.5,-2.267,-8.576> }
		triangle { <1.5,-2.267,-8.576>, <1.5,-3.655,-10.267>, <-1.5,-3.655,-10.267> }
		triangle { <-1.5,-2.267,-8.576>, <-1.5,-1.758,-5.524>, <1.5,-1.758,-5.524> }
		triangle { <1.5,-1.758,-5.524>, <1.5,-2.267,-8.576>, <-1.5,-2.267,-8.576> }
		triangle { <-1.5,-1.758,-5.524>, <-1.5,-1.784,-3.405>, <1.5,-1.784,-3.405> }
		triangle { <1.5,-1.784,-3.405>, <1.5,-1.758,-5.524>, <-1.5,-1.758,-5.524> }
		triangle { <1.5,-22.948,1.608>, <1.5,-22.303,2.523>, <1.5,-23.087,4.176> }
		triangle { <1.5,-23.087,4.176>, <1.5,-23.128,1.191>, <1.5,-22.948,1.608> }
		triangle { <1.5,-22.794,7.791>, <1.5,-23.087,4.176>, <1.5,-22.303,2.523> }
		triangle { <1.5,-22.303,2.523>, <1.5,-20.749,4.725>, <1.5,-22.794,7.791> }
		triangle { <1.5,-22.037,9.622>, <1.5,-22.794,7.791>, <1.5,-20.749,4.725> }
		triangle { <1.5,-20.749,4.725>, <1.5,-19.201,6.919>, <1.5,-22.037,9.622> }
		triangle { <1.5,-19.055,7.126>, <1.5,-20.379,9.85>, <1.5,-22.037,9.622> }
		triangle { <1.5,-22.037,9.622>, <1.5,-19.201,6.919>, <1.5,-19.055,7.126> }
		triangle { <1.5,-19.055,7.126>, <1.5,-17.099,8.614>, <1.5,-20.379,9.85> }
		triangle { <1.5,-17.099,8.614>, <1.5,-16.425,9.127>, <1.5,-18.265,9.539> }
		triangle { <1.5,-18.265,9.539>, <1.5,-20.379,9.85>, <1.5,-17.099,8.614> }
		triangle { <1.5,-6.754,-3.654>, <1.5,-7.108,-5.221>, <1.5,-1.758,-5.524> }
		triangle { <1.5,-1.758,-5.524>, <1.5,-1.784,-3.405>, <1.5,-6.754,-3.654> }
		triangle { <1.5,-1.784,-3.405>, <1.5,-6.75,-3.388>, <1.5,-6.754,-3.654> }
		triangle { <1.5,-2.267,-8.576>, <1.5,-1.758,-5.524>, <1.5,-7.108,-5.221> }
		triangle { <1.5,-7.108,-5.221>, <1.5,-7.656,-7.648>, <1.5,-2.267,-8.576> }
		triangle { <1.5,-7.656,-7.648>, <1.5,-8.083,-9.533>, <1.5,-3.655,-10.267> }
		triangle { <1.5,-3.655,-10.267>, <1.5,-2.267,-8.576>, <1.5,-7.656,-7.648> }
		triangle { <1.5,-5.609,-10.403>, <1.5,-3.655,-10.267>, <1.5,-8.083,-9.533> }
		triangle { <1.5,-8.083,-9.533>, <1.5,-8.089,-9.563>, <1.5,-5.609,-10.403> }
	}
}
#end
#end // ifndef (_87993_dot_dat)


//// Model weapon_008_laserpistol.ldr
#ifndef (weapon__008__laserpistol_dot_ldr)
#declare weapon__008__laserpistol_dot_ldr = object {
// Untitled
// Name: weapon_008_laserpistol.ldr
// Author: MLCad
// Unofficial Model
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	// 1 7  -11 8 0  0 -0.258819 -0.965926  0 0.965926 -0.258819  1 0 0 87993.dat
	object {
		_87993_dot_dat
		matrix <1-L3SW/18,0,0,0,1-L3SW/38.2124,0,0,0,1-L3SW/43.3076,0,L3SW/-3.78109,L3SW/-5.78856>
		matrix <0,0,1,-0.258819,0.965926,0,-0.965926,-0.258819,0,-11,8,0>
		material { L3Color7 }
	}
}
#end // ifndef (weapon__008__laserpistol_dot_ldr)


//// ModelData
#declare L3ModelBBoxMin = <-27.0187,-23.885,-9>;
#declare L3ModelBBoxMax = <24.7033,24.2341,9>;
#declare L3ModelBBoxCenter = (L3ModelBBoxMin+L3ModelBBoxMax)/2; // <-1.15768,0.17455,0>
#declare L3ModelBBoxSize = L3ModelBBoxMax-L3ModelBBoxMin; // <51.722,48.1191,18>
#declare L3FloorY = L3ModelBBoxMax.y;

//// ModelObject weapon_008_laserpistol.ldr
object { weapon__008__laserpistol_dot_ldr }



//// Statistics
//               PARTS             P         Total
// DAT files:        2            19            22
// POV Equivs:       -            10 (53%)
// Model has 2 parts (3 studs)

//// IncludeFile AtEnd
#include "weapons_camera.inc"

//// End
