// Generated by L3P v1.4 BETA 20131202 (Win32)  (C) 1998-2013 Lars C. Hassing SP.lars@AM.hassings.dk
// L3P website:  http://www.hassings.dk/l3/l3p.html
// LDraw.org:    http://www.ldraw.org
// Date:         Mon Apr 23 21:59:44 2018
// Input file:   D:\Datsville RPG\RPG Maker MV\povray_source\pov_combat_test\infrastructure\infrastructure_signstop.ldr
// Title:        Stop Sign
// Author:       Michael Horvath
// ModelDir:     D:\Datsville RPG\RPG Maker MV\povray_source\pov_combat_test\infrastructure
// WorkDir:      D:\Datsville RPG\RPG Maker MV\povray_source\pov_combat_test\infrastructure
// LDRAWDIR:     C:\Users\Public\Documents\LDraw (LDRAWDIR environment variable)
// SearchDirs:   (Default)
// SearchDir1:   D:\Datsville RPG\RPG Maker MV\povray_source\pov_combat_test\infrastructure\ (0x10)
// SearchDir2:   C:\Users\Public\Documents\LDraw\P\ (0x9)
// SearchDir3:   C:\Users\Public\Documents\LDraw\PARTS\ (0x4)
// SearchDir4:   C:\Users\Public\Documents\LDraw\MODELS\ (0x0)
// ldconfig.ldr: C:\Users\Public\Documents\LDraw\ldconfig.ldr
// Commandline:  "E:\Programs Windows\LDraw\l3p14beta\L3P20131202.EXE" "D:\Datsville RPG\RPG Maker MV\povray_source\pov_combat_test\infrastructure\infrastructure_signstop.ldr" "D:\Datsville RPG\RPG Maker MV\povray_source\pov_combat_test\infrastructure\infrastructure_signstop_figure.pov" -o -ic -il -ibinfrastructure_figure.inc

#if (version < 3.1)
	#error "This POV code requires at least version 3.1\n"
#end

//// Defines

#declare L3Version = 1.4;

#declare L3Quality = 2;  // Quality level, 0=BBox, 1=no refr, 2=normal, 3=studlogo, 4=stud2logo

#declare L3SW = 0.5;  // Width of seam between two bricks

#declare L3Studs = 1;  // 1=on 0=off

#declare L3Bumps = 0;  // 1=on 0=off


#declare L3Ambient = 0.4;
#declare L3Diffuse = 0.4;
#declare L3Ior     = 1.25;
#declare L3NormalBumps = normal { bumps 0.01 scale 20 }
#declare L3NormalSlope = normal { bumps 0.3 scale 0.5 }


#declare L3SWT = (L3SW ? L3SW : 0.001);  // At least a small seam when transparent

#declare L3Logo = union {
	sphere {<-59,0,-96>,6}
	cylinder {<-59,0,-96>,<59,0,-122>,6 open}
	sphere {<59,0,-122>,6}
	cylinder {<59,0,-122>,<59,0,-84>,6 open}
	sphere {<59,0,-84>,6}

	sphere {<-59,0,-36>,6}
	cylinder {<-59,0,-36>,<-59,0,1>,6 open}
	sphere {<-59,0,1>,6}
	cylinder {<0,0,-49>,<0,0,-25>,6 open}
	sphere {<0,0,-25>,6}
	sphere {<59,0,-62>,6}
	cylinder {<59,0,-62>,<59,0,-24>,6 open}
	sphere {<59,0,-24>,6}
	cylinder {<-59,0,-36>,<59,0,-62>,6 open}

	sphere {<-35.95,0,57>,6}
	torus {18.45,6 clipped_by{plane{<40,0,-9>,0}} translate<-40,0,39>}
	cylinder {<-44.05,0,21>,<35.95,0,3>,6 open}
	torus {18.45,6 clipped_by{plane{<-40,0,9>,0}} translate<40,0,21>}
	cylinder {<44.05,0,39>,<0,0,49>,6 open}
	sphere {<0,0,49>,6}
	cylinder {<0,0,49>,<0,0,34>,6 open}
	sphere {<0,0,34>,6}

	torus {18.45,6 clipped_by{plane{<40,0,-9>,0}} translate<-40,0,99>}
	cylinder {<-44.05,0,81>,<35.95,0,63>,6 open}
	torus {18.45,6 clipped_by{plane{<-40,0,9>,0}} translate<40,0,81>}
	cylinder {<44.05,0,99>,<-35.95,0,117>,6 open}

	scale 4.5/128
}


//// IncludeFile AtBeginning
#include "infrastructure_figure.inc"



//// Finishes
#ifndef (L3FinishOpaque)
#declare L3FinishOpaque = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.5
		phong_size 40
		reflection 0.08
	#end
}
#end

#ifndef (L3FinishChrome)
#declare L3FinishChrome = finish {
	ambient 0.25
	diffuse 0.6
	#if (L3Quality >= 2)
		brilliance 5
		metallic
		specular 0.80
		roughness 1/100
		reflection 0.65
	#end
}
#end

#ifndef (L3FinishPearlescent)
//Not supported yet, using Opaque
#declare L3FinishPearlescent = finish { L3FinishOpaque }
#end

#ifndef (L3FinishRubber)
#declare L3FinishRubber = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.1
		phong_size 10
		reflection 0
	#end
}
#end

#ifndef (L3FinishMatte_metallic)
//Not supported yet, using Opaque
#declare L3FinishMatte_metallic = finish { L3FinishOpaque }
#end

#ifndef (L3FinishMetal)
//Not supported yet, using Opaque
#declare L3FinishMetal = finish { L3FinishOpaque }
#end

#ifndef (L3FinishTransparent)
#declare L3FinishTransparent = finish {
	ambient L3Ambient
	diffuse L3Diffuse
	#if (L3Quality >= 2)
		phong 0.5
		phong_size 40
		reflection 0.2
	#end
}
#end



//// Macros
#ifndef (L3TextureOpaqueRGB)
#macro L3TextureOpaqueRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishOpaque }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureChromeRGB)
#macro L3TextureChromeRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishChrome }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TexturePearlescentRGB)
#macro L3TexturePearlescentRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishPearlescent }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureRubberRGB)
#macro L3TextureRubberRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishRubber }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureMatte_metallicRGB)
#macro L3TextureMatte_metallicRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishMatte_metallic }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureMetalRGB)
#macro L3TextureMetalRGB(r,g,b)
texture {
	pigment { rgb <r/255,g/255,b/255> }
	finish { L3FinishMetal }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureTransparentRGBA)
#macro L3TextureTransparentRGBA(r,g,b,a)
// Alpha -> Filter: 255 -> 1.00, 128 -> 0.85, 0 -> 0
#local f = (a >= 128 ? 0.85 + (a-128) * 0.15 / (255-128) : a * 0.85 / 255);
texture {
	pigment { rgb <r/255,g/255,b/255> #if (L3Quality > 1) filter f #end }
	finish { L3FinishTransparent }
	#if (L3Bumps & (L3Quality > 1)) normal { L3NormalBumps } #end
}
#end
#end

#ifndef (L3TextureSlope)
#macro L3TextureSlope(tex)
texture {
	tex
	#if (L3Quality > 1) normal { L3NormalSlope } #end
}
#end
#end

#ifndef (L3Material)
#macro L3Material(tex)
material {
	texture { tex }
}
#end
#end

#ifndef (L3MaterialT)
#macro L3MaterialT(tex)
material {
	texture { tex }
	#if (L3Quality > 1)
		interior { ior L3Ior }
	#end
}
#end
#end



//// Color 7 Light_Grey (from ldconfig.ldr)
#ifndef (L3Texture7)
#declare L3Texture7 = L3TextureOpaqueRGB(155,161,157)
#end
#ifndef (L3Texture7_slope)
#declare L3Texture7_slope = L3TextureSlope(L3Texture7)
#end
#ifndef (L3Color7)
#declare L3Color7 = L3Material(L3Texture7)
#end
#ifndef (L3Color7_slope)
#declare L3Color7_slope = L3Material(L3Texture7_slope)
#end


//// Color 15 White (from ldconfig.ldr)
#ifndef (L3Texture15)
#declare L3Texture15 = L3TextureOpaqueRGB(255,255,255)
#end
#ifndef (L3Texture15_slope)
#declare L3Texture15_slope = L3TextureSlope(L3Texture15)
#end
#ifndef (L3Color15)
#declare L3Color15 = L3Material(L3Texture15)
#end
#ifndef (L3Color15_slope)
#declare L3Color15_slope = L3Material(L3Texture15_slope)
#end


//// Color 4 Red (from ldconfig.ldr)
#ifndef (L3Texture4)
#declare L3Texture4 = L3TextureOpaqueRGB(201,26,9)
#end
#ifndef (L3Texture4_slope)
#declare L3Texture4_slope = L3TextureSlope(L3Texture4)
#end
#ifndef (L3Color4)
#declare L3Color4 = L3Material(L3Texture4)
#end
#ifndef (L3Color4_slope)
#declare L3Color4_slope = L3Material(L3Texture4_slope)
#end


//// Primitive rect.dat
#ifndef (rect_dot_dat)
#declare rect_dot_dat = object {
// Rectangle
// Name: rect.dat
// Author: James Jessiman
// !LDRAW_ORG Primitive UPDATE 2010-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2002-04-05 [hafhead] Added BFC statement
// !HISTORY 2002-04-25 [PTadmin] Official Update 2002-02
// !HISTORY 2007-06-24 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2010-01-17 [mikeheide] changed winding to CCW
// !HISTORY 2010-04-05 [PTadmin] Official Update 2010-01
	mesh {
		triangle { <-1,0,1>, <-1,0,-1>, <1,0,-1> }
		triangle { <1,0,-1>, <1,0,1>, <-1,0,1> }
	}
}
#end // ifndef (rect_dot_dat)


//// Primitive box5.dat
#ifndef (box5_dot_dat)
#declare box5_dot_dat = object {
// Box with 5 Faces and All Edges
// Name: box5.dat
// Author: James Jessiman
// !LDRAW_ORG Primitive UPDATE 2012-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2002-04-03 [sbliss] Modified for BFC compliance
// !HISTORY 2002-04-25 [PTadmin] Official Update 2002-02
// !HISTORY 2007-06-24 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2012-02-16 [Philo] Changed to CCW
// !HISTORY 2012-03-30 [PTadmin] Official Update 2012-01
	mesh {
		triangle { <-1,1,1>, <1,1,1>, <1,1,-1> }
		triangle { <1,1,-1>, <-1,1,-1>, <-1,1,1> }
		triangle { <-1,1,1>, <-1,0,1>, <1,0,1> }
		triangle { <1,0,1>, <1,1,1>, <-1,1,1> }
		triangle { <-1,1,-1>, <-1,0,-1>, <-1,0,1> }
		triangle { <-1,0,1>, <-1,1,1>, <-1,1,-1> }
		triangle { <1,1,-1>, <1,0,-1>, <-1,0,-1> }
		triangle { <-1,0,-1>, <-1,1,-1>, <1,1,-1> }
		triangle { <1,1,1>, <1,0,1>, <1,0,-1> }
		triangle { <1,0,-1>, <1,1,-1>, <1,1,1> }
	}
}
#end // ifndef (box5_dot_dat)


//// Primitive 2-4cyli.dat
#ifndef (_2_dash_4cyli_dot_dat)
#declare _2_dash_4cyli_dot_dat = cylinder { <0,0,0>, <0,1,0>, 1 open clipped_by { plane { -z, 0 } } }
#end // ifndef (_2_dash_4cyli_dot_dat)


//// Primitive 2-4disc.dat
#ifndef (_2_dash_4disc_dot_dat)
#declare _2_dash_4disc_dot_dat = disc { <0,0,0>, <0,1,0>, 1 clipped_by { box { <-2,-1,0>, <2,1,2> } } }
#end // ifndef (_2_dash_4disc_dot_dat)


//// Primitive clip4.dat
#ifndef (clip4_dot_dat)
#declare clip4_dot_dat = union {
// Clip for Roadsign and Click-Hinge
// Name: clip4.dat
// Author: Franklin W. Cain [fwcain]
// !LDRAW_ORG Primitive UPDATE 2004-04
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2002-08-18 [PTadmin] Official Update 2002-04
// !HISTORY 2004-10-01 [sbliss] BFC'ed
// !HISTORY 2004-11-06 [PTadmin] Official Update 2004-04
// !HISTORY 2007-06-24 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
	object { box5_dot_dat matrix <1,0,0,0,0,2,0,-4,0,0,0,-6> }
// 
	mesh {
		triangle { <-4,-4,-6>, <-4,-4,1>, <-7,-4,1> }
		triangle { <-7,-4,1>, <-7,-4,-6>, <-4,-4,-6> }
		triangle { <7,-4,1>, <4,-4,1>, <4,-4,-6> }
		triangle { <4,-4,-6>, <7,-4,-6>, <7,-4,1> }
		triangle { <-7,4,1>, <-4,4,1>, <-4,4,-6> }
		triangle { <-4,4,-6>, <-7,4,-6>, <-7,4,1> }
		triangle { <4,4,-6>, <4,4,1>, <7,4,1> }
		triangle { <7,4,1>, <7,4,-6>, <4,4,-6> }
		triangle { <-7,-4,1>, <-4.001,-4,1>, <-3.659,-4,1.94> }
		triangle { <-3.659,-4,1.94>, <-6.479,-4,2.966>, <-7,-4,1> }
		triangle { <3.659,-4,1.94>, <4.001,-4,1>, <7,-4,1> }
		triangle { <7,-4,1>, <6.479,-4,2.966>, <3.659,-4,1.94> }
		triangle { <-3.659,4,1.94>, <-4.001,4,1>, <-7,4,1> }
		triangle { <-7,4,1>, <-6.479,4,2.966>, <-3.659,4,1.94> }
		triangle { <7,4,1>, <4.001,4,1>, <3.659,4,1.94> }
		triangle { <3.659,4,1.94>, <6.479,4,2.966>, <7,4,1> }
// 
		triangle { <-4,4,1>, <-4,-4,1>, <-4,-4,-6> }
		triangle { <-4,-4,-6>, <-4,4,-6>, <-4,4,1> }
		triangle { <4,-4,-6>, <4,-4,1>, <4,4,1> }
		triangle { <4,4,1>, <4,4,-6>, <4,-4,-6> }
		triangle { <-7,-4,-6>, <-7,-4,1>, <-7,4,1> }
		triangle { <-7,4,1>, <-7,4,-6>, <-7,-4,-6> }
		triangle { <7,4,1>, <7,-4,1>, <7,-4,-6> }
		triangle { <7,-4,-6>, <7,4,-6>, <7,4,1> }
		triangle { <-6.479,4,2.966>, <-7,4,1>, <-7,-4,1> }
		triangle { <-7,-4,1>, <-6.479,-4,2.966>, <-6.479,4,2.966> }
		triangle { <7,-4,1>, <7,4,1>, <6.479,4,2.966> }
		triangle { <6.479,4,2.966>, <6.479,-4,2.966>, <7,-4,1> }
		triangle { <-4.001,-4,1>, <-4.001,4,1>, <-3.659,4,1.94> }
		triangle { <-3.659,4,1.94>, <-3.659,-4,1.94>, <-4.001,-4,1> }
		triangle { <3.659,4,1.94>, <4.001,4,1>, <4.001,-4,1> }
		triangle { <4.001,-4,1>, <3.659,-4,1.94>, <3.659,4,1.94> }
// 
// 
// 
// 
	}
	object { _2_dash_4cyli_dot_dat matrix <-1.41,0,0.513,0,8,0,0.513,0,1.41,-5.069,-4,2.453> }
	object { _2_dash_4cyli_dot_dat matrix <1.41,0,0.513,0,8,0,-0.513,0,1.41,5.069,-4,2.453> }
	object { _2_dash_4disc_dot_dat matrix <-1.41,0,0.513,0,8,0,0.513,0,1.41,-5.069,-4,2.453> }
	object { _2_dash_4disc_dot_dat matrix <1.41,0,0.513,0,-8,0,-0.513,0,1.41,5.069,4,2.453> }
	object { _2_dash_4disc_dot_dat matrix <1.41,0,0.513,0,8,0,-0.513,0,1.41,5.069,-4,2.453> }
	object { _2_dash_4disc_dot_dat matrix <-1.41,0,0.513,0,-8,0,0.513,0,1.41,-5.069,4,2.453> }
// 
}
#end // ifndef (clip4_dot_dat)


//// Part s\30260s01.dat
#ifndef (s_slash_30260s01_dot_dat)
#declare s_slash_30260s01_dot_dat = #if (L3Quality = 0) box { <-20,-20,-9>, <20,20,4.376> } #else union {
// ~Roadsign Clip-on  2 x  2 Octagonal without Pattern Area
// Name: s\30260s01.dat
// Author: John Van Zwieten [jvan]
// !LDRAW_ORG Subpart UPDATE 2011-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 1999-05-17 [PTadmin] Official Update 1999-03
// !HISTORY 2002-02-21 [fwcain] "clip-on" into shared primitive, fixing gaps.
// !HISTORY 2002-08-18 [PTadmin] Official Update 2002-04
// !HISTORY 2007-09-10 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2011-12-08 [Rolf] BFC'ed, renamed from 890s01
// !HISTORY 2011-12-29 [PTadmin] Official Update 2011-02
	object { rect_dot_dat matrix <0,0,1.5,-1,0,0,0,-8,0,20,0,-7.5> }
	object { rect_dot_dat matrix <0,0,1.5,1,0,0,0,8,0,-20,0,-7.5> }
	object { rect_dot_dat matrix <0,0,1.5,0,-1,0,8,0,0,0,20,-7.5> }
	object { rect_dot_dat matrix <0,0,1.5,0,1,0,-8,0,0,0,-20,-7.5> }
	mesh {
		triangle { <20,8,-9>, <8,20,-9>, <8,20,-6> }
		triangle { <8,20,-6>, <20,8,-6>, <20,8,-9> }
		triangle { <-20,8,-6>, <-8,20,-6>, <-8,20,-9> }
		triangle { <-8,20,-9>, <-20,8,-9>, <-20,8,-6> }
		triangle { <20,-8,-6>, <8,-20,-6>, <8,-20,-9> }
		triangle { <8,-20,-9>, <20,-8,-9>, <20,-8,-6> }
		triangle { <-20,-8,-9>, <-8,-20,-9>, <-8,-20,-6> }
		triangle { <-8,-20,-6>, <-20,-8,-6>, <-20,-8,-9> }
		triangle { <-20,-8,-6>, <20,-8,-6>, <20,8,-6> }
		triangle { <20,8,-6>, <-20,8,-6>, <-20,-8,-6> }
		triangle { <-20,-8,-6>, <-8,-20,-6>, <8,-20,-6> }
		triangle { <8,-20,-6>, <20,-8,-6>, <-20,-8,-6> }
		triangle { <20,8,-6>, <8,20,-6>, <-8,20,-6> }
		triangle { <-8,20,-6>, <-20,8,-6>, <20,8,-6> }
	}
	object { clip4_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
}
#end
#end // ifndef (s_slash_30260s01_dot_dat)


//// Primitive 1-4disc.dat
#ifndef (_1_dash_4disc_dot_dat)
#declare _1_dash_4disc_dot_dat = disc { <0,0,0>, <0,1,0>, 1 clipped_by { plane { -x, 0 } plane { -z, 0 } } }
#end // ifndef (_1_dash_4disc_dot_dat)


//// Primitive 1-4ndis.dat
#ifndef (_1_dash_4ndis_dot_dat)
#declare _1_dash_4ndis_dot_dat = disc { <0,0,0>, <0,1,0>, 2, 1 clipped_by { box { <0,-1,0>, <1,1,1> } } }
#end // ifndef (_1_dash_4ndis_dot_dat)


//// Primitive 2-4ndis.dat
#ifndef (_2_dash_4ndis_dot_dat)
#declare _2_dash_4ndis_dot_dat = disc { <0,0,0>, <0,1,0>, 2, 1 clipped_by { box { <-1,-1,0>, <1,1,1> } } }
#end // ifndef (_2_dash_4ndis_dot_dat)


//// Primitive 1-8disc.dat
#ifndef (_1_dash_8disc_dot_dat)
#declare _1_dash_8disc_dot_dat = disc {
	<0,0,0>, <0,1,0>, 1
	clipped_by { plane { -z,0 } plane { <-1,0,1>,0 } }
}
#end // ifndef (_1_dash_8disc_dot_dat)


//// Primitive 1-8ndis.dat
#ifndef (_1_dash_8ndis_dot_dat)
#declare _1_dash_8ndis_dot_dat = disc {
	<0,0,0>, <0,1,0>, 2, 1
	clipped_by { plane { x, 1 } plane { -z, 0 } plane { <-1,0,1>, 0 } }
}
#end // ifndef (_1_dash_8ndis_dot_dat)


//// Part 30260p01.dat
#ifndef (_30260p01_dot_dat)
#declare _30260p01_dot_dat = #if (L3Quality = 0) box { <-20,-20,-9>, <20,20,4.376> } #else union {
// Roadsign Clip-on  2 x  2 Octagonal w/ Red Stop Sign Pattern
// Name: 30260p01.dat
// Author: Franklin W. Cain [fwcain]
// !LDRAW_ORG Part UPDATE 2011-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !CMDLINE -c15
// !HISTORY 2003-08-01 [PTadmin] Official Update 2003-02
// !HISTORY 2007-07-23 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2011-12-08 [Rolf] BFC'ed, renamed from 890p01
// !HISTORY 2011-12-29 [PTadmin] Official Update 2011-02
	object { s_slash_30260s01_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
	mesh {
		triangle { <-8,-20,-9>, <-7,-18,-9>, <7,-18,-9> }
		triangle { <7,-18,-9>, <8,-20,-9>, <-8,-20,-9> }
		triangle { <8,20,-9>, <7,18,-9>, <-7,18,-9> }
		triangle { <-7,18,-9>, <-8,20,-9>, <8,20,-9> }
		triangle { <-20,8,-9>, <-18,7,-9>, <-18,-7,-9> }
		triangle { <-18,-7,-9>, <-20,-8,-9>, <-20,8,-9> }
		triangle { <20,-8,-9>, <18,-7,-9>, <18,7,-9> }
		triangle { <18,7,-9>, <20,8,-9>, <20,-8,-9> }
		triangle { <-20,-8,-9>, <-18,-7,-9>, <-7,-18,-9> }
		triangle { <-7,-18,-9>, <-8,-20,-9>, <-20,-8,-9> }
		triangle { <8,-20,-9>, <7,-18,-9>, <18,-7,-9> }
		triangle { <18,-7,-9>, <20,-8,-9>, <8,-20,-9> }
		triangle { <-8,20,-9>, <-7,18,-9>, <-18,7,-9> }
		triangle { <-18,7,-9>, <-20,8,-9>, <-8,20,-9> }
		triangle { <20,8,-9>, <18,7,-9>, <7,18,-9> }
		triangle { <7,18,-9>, <8,20,-9>, <20,8,-9> }
	}
	mesh {
		triangle { <-7,-18,-9>, <-18,-7,-9>, <18,-7,-9> }
		triangle { <18,-7,-9>, <7,-18,-9>, <-7,-18,-9> }
		triangle { <7,18,-9>, <18,7,-9>, <-18,7,-9> }
		triangle { <-18,7,-9>, <-7,18,-9>, <7,18,-9> }
		triangle { <-0.75,7,-9>, <0.75,7,-9>, <0.75,-7,-9> }
		triangle { <0.75,-7,-9>, <-0.75,-7,-9>, <-0.75,7,-9> }
		triangle { <-7.75,-7,-9>, <-9.25,-7,-9>, <-9.25,7,-9> }
		triangle { <-9.25,7,-9>, <-7.75,7,-9>, <-7.75,-7,-9> }
		triangle { <7.75,7,-9>, <9.25,7,-9>, <9.25,-7,-9> }
		triangle { <9.25,-7,-9>, <7.75,-7,-9>, <7.75,7,-9> }
		triangle { <-16.25,-7,-9>, <-18,-7,-9>, <-18,7,-9> }
		triangle { <-18,7,-9>, <-16.25,7,-9>, <-16.25,-7,-9> }
		triangle { <16.25,7,-9>, <18,7,-9>, <18,-7,-9> }
		triangle { <18,-7,-9>, <16.25,-7,-9>, <16.25,7,-9> }
// Letter "S"
		material { L3Color4 }
	}
	mesh {
		triangle { <-13.25,-7,-9>, <-13.25,-5,-9>, <-12.25,-5,-9> }
		triangle { <-12.25,-5,-9>, <-12.25,-7,-9>, <-13.25,-7,-9> }
		triangle { <-12.25,7,-9>, <-12.25,5,-9>, <-13.25,5,-9> }
		triangle { <-13.25,5,-9>, <-13.25,7,-9>, <-12.25,7,-9> }
		triangle { <-9.25,-4,-9>, <-12.25,-4,-9>, <-12.25,-2.5,-9> }
		triangle { <-12.25,-2.5,-9>, <-9.25,-2.5,-9>, <-9.25,-4,-9> }
		triangle { <-9.25,2.5,-9>, <-12.25,2.5,-9>, <-12.25,4,-9> }
		triangle { <-12.25,4,-9>, <-9.25,4,-9>, <-9.25,2.5,-9> }
	}
	mesh {
		triangle { <-12.25,-4,-9>, <-13.25,-4,-9>, <-13.25,-2.5,-9> }
		triangle { <-13.25,-2.5,-9>, <-12.25,-2.5,-9>, <-12.25,-4,-9> }
		triangle { <-12.25,2.5,-9>, <-13.25,2.5,-9>, <-13.25,4,-9> }
		triangle { <-13.25,4,-9>, <-12.25,4,-9>, <-12.25,2.5,-9> }
		material { L3Color4 }
	}
	mesh {
		triangle { <-13.25,-4,-9>, <-16.25,-4,-9>, <-16.25,-2.5,-9> }
		triangle { <-16.25,-2.5,-9>, <-13.25,-2.5,-9>, <-13.25,-4,-9> }
		triangle { <-13.25,2.5,-9>, <-16.25,2.5,-9>, <-16.25,4,-9> }
		triangle { <-16.25,4,-9>, <-13.25,4,-9>, <-13.25,2.5,-9> }
	}
	mesh {
		triangle { <-13.25,-2.5,-9>, <-9.25,-0.5,-9>, <-9.25,-2.5,-9> }
		triangle { <-12.25,2.5,-9>, <-16.25,0.5,-9>, <-16.25,2.5,-9> }
		triangle { <-9.25,-0.5,-9>, <-13.25,-2.5,-9>, <-10.129,0.379,-9> }
		triangle { <-16.25,0.5,-9>, <-12.25,2.5,-9>, <-15.371,-0.379,-9> }
		material { L3Color4 }
	}
	mesh {
		triangle { <-15.371,-0.379,-9>, <-12.25,2.5,-9>, <-10.129,0.379,-9> }
		triangle { <-10.129,0.379,-9>, <-13.25,-2.5,-9>, <-15.371,-0.379,-9> }
	}
	object { _1_dash_4disc_dot_dat matrix <-3,0,0,0,0,1,0,-3,0,-13.25,-4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <-3,0,0,0,0,1,0,-3,0,-13.25,-4,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <-3,0,0,0,0,1,0,3,0,-13.25,4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <-3,0,0,0,0,1,0,3,0,-13.25,4,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <3,0,0,0,0,1,0,-3,0,-12.25,-4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <3,0,0,0,0,1,0,-3,0,-12.25,-4,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <3,0,0,0,0,1,0,3,0,-12.25,4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <3,0,0,0,0,1,0,3,0,-12.25,4,-9> material { L3Color4 } }
	object { _2_dash_4disc_dot_dat matrix <0.5,0,0,0,0,1,0,-1,0,-12.75,-4,-9> material { L3Color4 } }
	object { _2_dash_4ndis_dot_dat matrix <0.5,0,0,0,0,1,0,-1,0,-12.75,-4,-9> }
	object { _2_dash_4disc_dot_dat matrix <0.5,0,0,0,0,1,0,1,0,-12.75,4,-9> material { L3Color4 } }
	object { _2_dash_4ndis_dot_dat matrix <0.5,0,0,0,0,1,0,1,0,-12.75,4,-9> }
	object { _1_dash_8disc_dot_dat matrix <-3,0,0,0,0,1,0,3,0,-13.25,-2.5,-9> }
	object { _1_dash_8ndis_dot_dat matrix <-3,0,0,0,0,1,0,3,0,-13.25,-2.5,-9> material { L3Color4 } }
	object { _1_dash_8disc_dot_dat matrix <3,0,0,0,0,1,0,-3,0,-12.25,2.5,-9> }
	object { _1_dash_8ndis_dot_dat matrix <3,0,0,0,0,1,0,-3,0,-12.25,2.5,-9> material { L3Color4 } }
// Letter "T"
	mesh {
		triangle { <-0.75,-7,-9>, <-7.75,-7,-9>, <-7.75,-4,-9> }
		triangle { <-7.75,-4,-9>, <-0.75,-4,-9>, <-0.75,-7,-9> }
		triangle { <-2.75,-4,-9>, <-5.75,-4,-9>, <-5.75,7,-9> }
		triangle { <-5.75,7,-9>, <-2.75,7,-9>, <-2.75,-4,-9> }
	}
	mesh {
		triangle { <-0.75,-4,-9>, <-2.75,-4,-9>, <-2.75,7,-9> }
		triangle { <-2.75,7,-9>, <-0.75,7,-9>, <-0.75,-4,-9> }
		triangle { <-5.75,-4,-9>, <-7.75,-4,-9>, <-7.75,7,-9> }
		triangle { <-7.75,7,-9>, <-5.75,7,-9>, <-5.75,-4,-9> }
// Letter "O"
		material { L3Color4 }
	}
	mesh {
		triangle { <0.75,4,-9>, <3.75,4,-9>, <3.75,-4,-9> }
		triangle { <3.75,-4,-9>, <0.75,-4,-9>, <0.75,4,-9> }
		triangle { <4.75,4,-9>, <7.75,4,-9>, <7.75,-4,-9> }
		triangle { <7.75,-4,-9>, <4.75,-4,-9>, <4.75,4,-9> }
	}
	mesh {
		triangle { <3.75,4,-9>, <4.75,4,-9>, <4.75,-4,-9> }
		triangle { <4.75,-4,-9>, <3.75,-4,-9>, <3.75,4,-9> }
		material { L3Color4 }
	}
	mesh {
		triangle { <3.75,-5,-9>, <4.75,-5,-9>, <4.75,-7,-9> }
		triangle { <4.75,-7,-9>, <3.75,-7,-9>, <3.75,-5,-9> }
		triangle { <3.75,7,-9>, <4.75,7,-9>, <4.75,5,-9> }
		triangle { <4.75,5,-9>, <3.75,5,-9>, <3.75,7,-9> }
	}
	object { _1_dash_4disc_dot_dat matrix <-3,0,0,0,0,1,0,-3,0,3.75,-4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <-3,0,0,0,0,1,0,-3,0,3.75,-4,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <-3,0,0,0,0,1,0,3,0,3.75,4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <-3,0,0,0,0,1,0,3,0,3.75,4,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <3,0,0,0,0,1,0,-3,0,4.75,-4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <3,0,0,0,0,1,0,-3,0,4.75,-4,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <3,0,0,0,0,1,0,3,0,4.75,4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <3,0,0,0,0,1,0,3,0,4.75,4,-9> material { L3Color4 } }
	object { _2_dash_4disc_dot_dat matrix <0.5,0,0,0,0,1,0,-1,0,4.25,-4,-9> material { L3Color4 } }
	object { _2_dash_4ndis_dot_dat matrix <0.5,0,0,0,0,1,0,-1,0,4.25,-4,-9> }
	object { _2_dash_4disc_dot_dat matrix <0.5,0,0,0,0,1,0,1,0,4.25,4,-9> material { L3Color4 } }
	object { _2_dash_4ndis_dot_dat matrix <0.5,0,0,0,0,1,0,1,0,4.25,4,-9> }
// Letter "P"
	mesh {
		triangle { <9.25,7,-9>, <12.25,7,-9>, <12.25,-7,-9> }
		triangle { <12.25,-7,-9>, <9.25,-7,-9>, <9.25,7,-9> }
	}
	mesh {
		triangle { <12.25,7,-9>, <16.25,7,-9>, <16.25,2,-9> }
		triangle { <16.25,2,-9>, <12.25,2,-9>, <12.25,7,-9> }
		material { L3Color4 }
	}
	mesh {
		triangle { <12.25,-4,-9>, <13.25,-4,-9>, <13.25,-7,-9> }
		triangle { <13.25,-7,-9>, <12.25,-7,-9>, <12.25,-4,-9> }
	}
	mesh {
		triangle { <12.25,-2,-9>, <13.25,-2,-9>, <13.25,-3,-9> }
		triangle { <13.25,-3,-9>, <12.25,-3,-9>, <12.25,-2,-9> }
		material { L3Color4 }
	}
	mesh {
		triangle { <12.25,2,-9>, <13.25,2,-9>, <13.25,-1,-9> }
		triangle { <13.25,-1,-9>, <12.25,-1,-9>, <12.25,2,-9> }
		triangle { <13.25,-1,-9>, <16.25,-1,-9>, <16.25,-4,-9> }
		triangle { <16.25,-4,-9>, <13.25,-4,-9>, <13.25,-1,-9> }
	}
	object { _1_dash_4disc_dot_dat matrix <3,0,0,0,0,1,0,-3,0,13.25,-4,-9> }
	object { _1_dash_4ndis_dot_dat matrix <3,0,0,0,0,1,0,-3,0,13.25,-4,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <3,0,0,0,0,1,0,3,0,13.25,-1,-9> }
	object { _1_dash_4ndis_dot_dat matrix <3,0,0,0,0,1,0,3,0,13.25,-1,-9> material { L3Color4 } }
	object { _1_dash_4disc_dot_dat matrix <1,0,0,0,0,1,0,-1,0,12.25,-3,-9> material { L3Color4 } }
	object { _1_dash_4ndis_dot_dat matrix <1,0,0,0,0,1,0,-1,0,12.25,-3,-9> }
	object { _1_dash_4disc_dot_dat matrix <1,0,0,0,0,1,0,1,0,12.25,-2,-9> material { L3Color4 } }
	object { _1_dash_4ndis_dot_dat matrix <1,0,0,0,0,1,0,1,0,12.25,-2,-9> }
}
#end
#end // ifndef (_30260p01_dot_dat)


//// Primitive stud4.dat
#ifndef (stud4_dot_dat)
#declare stud4_dot_dat = difference {
	cylinder { <0,0,0>, <0,-4,0>, 8 }
	cylinder { <0,1,0>, <0,-5,0>, 6 }
}
#end // ifndef (stud4_dot_dat)


//// Part 3068a.dat
#ifndef (_3068a_dot_dat)
#declare _3068a_dot_dat = #if (L3Quality = 0) box { <-20,0,-20>, <20,8,20> } #else union {
// Tile  2 x  2 without Groove
// Name: 3068a.dat
// Author: James Jessiman
// !LDRAW_ORG Part UPDATE 2003-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CW
// !HISTORY 2003-06-16 [Steffen] BFCed
// !HISTORY 2003-08-01 [PTadmin] Official Update 2003-02
// !HISTORY 2007-06-13 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
	#if (L3Studs)
		object { stud4_dot_dat matrix <1,0,0,0,-1,0,0,0,1,0,4,0> }
// BFC INVERTNEXT
	#end
	object { box5_dot_dat matrix <16,0,0,0,-4,0,0,0,16,0,8,0> }
	mesh {
		triangle { <-20,8,20>, <-16,8,16>, <16,8,16> }
		triangle { <16,8,16>, <20,8,20>, <-20,8,20> }
		triangle { <20,8,-20>, <16,8,-16>, <-16,8,-16> }
		triangle { <-16,8,-16>, <-20,8,-20>, <20,8,-20> }
		triangle { <20,8,20>, <16,8,16>, <16,8,-16> }
		triangle { <16,8,-16>, <20,8,-20>, <20,8,20> }
		triangle { <-20,8,-20>, <-16,8,-16>, <-16,8,16> }
		triangle { <-16,8,16>, <-20,8,20>, <-20,8,-20> }
	}
	object { box5_dot_dat matrix <20,0,0,0,-8,0,0,0,20,0,8,0> }
}
#end
#end // ifndef (_3068a_dot_dat)


//// Primitive 4-4cyli.dat
#ifndef (_4_dash_4cyli_dot_dat)
#declare _4_dash_4cyli_dot_dat = cylinder { <0,0,0>, <0,1,0>, 1 open }
#end // ifndef (_4_dash_4cyli_dot_dat)


//// Primitive 4-4disc.dat
#ifndef (_4_dash_4disc_dot_dat)
#declare _4_dash_4disc_dot_dat = disc { <0,0,0>, <0,1,0>, 1 }
#end // ifndef (_4_dash_4disc_dot_dat)


//// Primitive stud.dat
#ifndef (stud_dot_dat)
#declare stud_dot_dat = 
#if (L3Quality >= 3)
union {
#end
	cylinder { <0,0,0>, <0,-4,0>, 6 }
#if (L3Quality >= 3)
	object { L3Logo translate <0,-4,0> }
}
#end
#end // ifndef (stud_dot_dat)


//// Part 30256.dat
#ifndef (_30256_dot_dat)
#declare _30256_dot_dat = #if (L3Quality = 0) box { <-20,-116.5,-20>, <20,8,20> } #else union {
// Tile  2 x  2 Roadsign Base
// Name: 30256.dat
// Author: Paul Easter [pneaster]
// !LDRAW_ORG Part UPDATE 2004-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CW
// !KEYWORDS traffic, road, signs, spot light, spotlight, post, pole, stand, bar
// !HISTORY 2004-04-22 [PTadmin] Official Update 2004-02
// !HISTORY 2007-06-07 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
	object { _3068a_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,0,0> }
	object { _4_dash_4cyli_dot_dat matrix <6.125,0,0,0,-4,0,0,0,6.125,0,0,0> }
	object { _4_dash_4disc_dot_dat matrix <6.125,0,0,0,1,0,0,0,6.125,0,-4,0> }
	object { _4_dash_4cyli_dot_dat matrix <4,0,0,0,-108.5,0,0,0,4,0,-4,0> }
	object { _4_dash_4disc_dot_dat matrix <6,0,0,0,-1,0,0,0,6,0,-112.5,0> }
	#if (L3Studs)
		object { stud_dot_dat matrix <1,0,0,0,1,0,0,0,1,0,-112.5,0> }
	#end
}
#end
#end // ifndef (_30256_dot_dat)


//// Model infrastructure_signstop.ldr
#ifndef (infrastructure__signstop_dot_ldr)
#declare infrastructure__signstop_dot_ldr = union {
// Stop Sign
// Name: infrastructure_signstop.ldr
// Author: Michael Horvath
// !LICENSE Redistributable under CC BY-SA version 3.0 : see https://creativecommons.org/licenses/by-sa/3.0/
// Unofficial Datsville Model
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	// 1 15  0 -116 0  1 0 0  0 1 0  0 0 1 30260p01.dat
	object {
		_30260p01_dot_dat
		matrix <1-L3SW/40,0,0,0,1-L3SW/40,0,0,0,1-L3SW/13.376,0,0,L3SW/-5.78547>
		matrix <1,0,0,0,1,0,0,0,1,0,-116,0>
		material { L3Color15 }
	}
	// 1 7  0 -8 0  1 0 0  0 1 0  0 0 1 30256.dat
	object {
		_30256_dot_dat
		matrix <1-L3SW/40,0,0,0,1-L3SW/124.5,0,0,0,1-L3SW/40,0,L3SW/-2.29493,0>
		matrix <1,0,0,0,1,0,0,0,1,0,-8,0>
		material { L3Color7 }
	}
}
#end // ifndef (infrastructure__signstop_dot_ldr)


//// ModelData
#declare L3ModelBBoxMin = <-20,-136,-20>;
#declare L3ModelBBoxMax = <20,0,20>;
#declare L3ModelBBoxCenter = (L3ModelBBoxMin+L3ModelBBoxMax)/2; // <0,-68,0>
#declare L3ModelBBoxSize = L3ModelBBoxMax-L3ModelBBoxMin; // <40,136,40>
#declare L3FloorY = L3ModelBBoxMax.y;

//// ModelObject infrastructure_signstop.ldr
object { infrastructure__signstop_dot_ldr rotate y * clock * 360 }



//// Statistics
//               PARTS             P         Total
// DAT files:        5            16            22
// POV Equivs:       -            11 (69%)
// Model has 3 parts (2 studs)

//// End
