set pov_source=D:\Datsville RPG\trunk\povray_source\pov_main_project\items
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\armor_001_samurai.ldr" "%pov_source%\armor_001_samurai.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\armor_002_plate.ldr" "%pov_source%\armor_002_plate.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\armor_003_shoulder.ldr" "%pov_source%\armor_003_shoulder.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\armor_004_backpacksmall.ldr" "%pov_source%\armor_004_backpacksmall.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\armor_005_backpacklarge.ldr" "%pov_source%\armor_005_backpacklarge.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_001_castle_01.ldr" "%pov_source%\helmet_001_castle_01.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_002_castle_02.ldr" "%pov_source%\helmet_002_castle_02.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_003_construction.ldr" "%pov_source%\helmet_003_construction.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_004_fireman.ldr" "%pov_source%\helmet_004_fireman.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_005_crown.ldr" "%pov_source%\helmet_005_crown.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_006_pith.ldr" "%pov_source%\helmet_006_pith.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_007_army.ldr" "%pov_source%\helmet_007_army.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_008_smallspikes.ldr" "%pov_source%\helmet_008_smallspikes.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_009_winged.ldr" "%pov_source%\helmet_009_winged.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_010_urukhai.ldr" "%pov_source%\helmet_010_urukhai.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_011_dragon.ldr" "%pov_source%\helmet_011_dragon.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_012_horned.ldr" "%pov_source%\helmet_012_horned.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_013_castle_03.ldr" "%pov_source%\helmet_013_castle_03.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_014_classicspace.ldr" "%pov_source%\helmet_014_classicspace.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_015_modernbike.ldr" "%pov_source%\helmet_015_modernbike.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_016_spanish.ldr" "%pov_source%\helmet_016_spanish.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_017_persian.ldr" "%pov_source%\helmet_017_persian.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_018_samurai.ldr" "%pov_source%\helmet_018_samurai.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_019_skateboard.ldr" "%pov_source%\helmet_019_skateboard.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_020_viking.ldr" "%pov_source%\helmet_020_viking.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_021_batwings.ldr" "%pov_source%\helmet_021_batwings.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\helmet_022_widebrim.ldr" "%pov_source%\helmet_022_widebrim.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_001_smallskull.ldr" "%pov_source%\shield_001_smallskull.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_002_scarab.ldr" "%pov_source%\shield_002_scarab.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_003_largeskull.ldr" "%pov_source%\shield_003_largeskull.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_004_smallroundplain.ldr" "%pov_source%\shield_004_smallroundplain.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_005_largeovoidsnake.ldr" "%pov_source%\shield_005_largeovoidsnake.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_006_largeovoiddragon.ldr" "%pov_source%\shield_006_largeovoiddragon.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_007_smallyellowcrown.ldr" "%pov_source%\shield_007_smallyellowcrown.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_008_smallbluelion.ldr" "%pov_source%\shield_008_smallbluelion.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_009_largehand.ldr" "%pov_source%\shield_009_largehand.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_010_largeoctogonalskull.ldr" "%pov_source%\shield_010_largeoctogonalskull.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_011_largeovalwhite.ldr" "%pov_source%\shield_011_largeovalwhite.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\shield_012_smallrohan.ldr" "%pov_source%\shield_012_smallrohan.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\armor_006_bandana.ldr" "%pov_source%\armor_006_bandana.pov" -o -ic -il -ibitems.inc -iearmor_camera.inc
pause
