set pov_source=D:\Datsville RPG\trunk\povray_source\pov_main_project\items
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_002_battleaxe.ldr" "%pov_source%\weapon_002_battleaxe.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_003_bow.ldr" "%pov_source%\weapon_003_bow.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_004_circularsaw.ldr" "%pov_source%\weapon_004_circularsaw.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_005_crossbow.ldr" "%pov_source%\weapon_005_crossbow.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_006_dynamite.ldr" "%pov_source%\weapon_006_dynamite.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_007_flintlockpistol.ldr" "%pov_source%\weapon_007_flintlockpistol.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_008_laserpistol.ldr" "%pov_source%\weapon_008_laserpistol.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_009_longblaster.ldr" "%pov_source%\weapon_009_longblaster.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_010_musket.ldr" "%pov_source%\weapon_010_musket.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_011_revolver.ldr" "%pov_source%\weapon_011_revolver.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_012_rifle.ldr" "%pov_source%\weapon_012_rifle.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_013_smallblaster.ldr" "%pov_source%\weapon_013_smallblaster.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_014_smiautomaticpistol.ldr" "%pov_source%\weapon_014_smiautomaticpistol.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_015_shortblaster.ldr" "%pov_source%\weapon_015_shortblaster.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_016_iceaxe.ldr" "%pov_source%\weapon_016_iceaxe.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_017_knife.ldr" "%pov_source%\weapon_017_knife.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_018_lance.ldr" "%pov_source%\weapon_018_lance.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_019_longbow.ldr" "%pov_source%\weapon_019_longbow.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_020_machinegun.ldr" "%pov_source%\weapon_020_machinegun.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_021_pharaohstaff.ldr" "%pov_source%\weapon_021_pharaohstaff.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_022_pickaxe.ldr" "%pov_source%\weapon_022_pickaxe.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_023_pike.ldr" "%pov_source%\weapon_023_pike.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_024_pipewrench.ldr" "%pov_source%\weapon_024_pipewrench.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_025_pitchfork.ldr" "%pov_source%\weapon_025_pitchfork.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_026_halberd.ldr" "%pov_source%\weapon_026_halberd.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_027_shovel.ldr" "%pov_source%\weapon_027_shovel.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_028_sledgehgammer.ldr" "%pov_source%\weapon_028_sledgehgammer.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_029_spear.ldr" "%pov_source%\weapon_029_spear.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_030_spearwithblades.ldr" "%pov_source%\weapon_030_spearwithblades.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_031_speargun.ldr" "%pov_source%\weapon_031_speargun.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_032_cutlass.ldr" "%pov_source%\weapon_032_cutlass.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_033_greatsword.ldr" "%pov_source%\weapon_033_greatsword.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_034_katana.ldr" "%pov_source%\weapon_034_katana.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_035_khopesh.ldr" "%pov_source%\weapon_035_khopesh.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_036_longsword.ldr" "%pov_source%\weapon_036_longsword.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_037_rapier.ldr" "%pov_source%\weapon_037_rapier.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_038_gladius.ldr" "%pov_source%\weapon_038_gladius.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_039_scimitar.ldr" "%pov_source%\weapon_039_scimitar.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_040_shortsword.ldr" "%pov_source%\weapon_040_shortsword.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_041_urukhai.ldr" "%pov_source%\weapon_041_urukhai.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_042_angledhilt.ldr" "%pov_source%\weapon_042_angledhilt.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_043_handaxe.ldr" "%pov_source%\weapon_043_handaxe.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_044_hammer.ldr" "%pov_source%\weapon_044_hammer.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_045_claw.ldr" "%pov_source%\weapon_045_claw.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_046_curvedblade.ldr" "%pov_source%\weapon_046_curvedblade.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_047_trident.ldr" "%pov_source%\weapon_047_trident.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
"E:\Programs Windows\l3p14beta\l3p.exe" "%pov_source%\weapon_048_whip.ldr" "%pov_source%\weapon_048_whip.pov" -o -ic -il -ibitems.inc -ieitems_camera.inc
pause
