// Generated By: LDView 4.2 Beta 1 Copyright (C) 2008 Travis Cobbs & Peter Bartfai
// See: http://ldview.sourceforge.net/
// Date: Sat Jul 12 05:13:30 2014
// Input LDraw File: color_test.ldr
// LDraw File Author: Michael Horvath
//
// This file was automatically generated from an LDraw file by the program
// LDView.  See comments above for further details.

#version 3.7;

#include "stdinc.inc"

global_settings
{
	assumed_gamma	1
}


light_source
{
	-z * 40960
	color rgb 1
	rotate		-x * 60
	rotate		+y * 45
	parallel
}

background { color srgbf 1 }

#local cam_aspc =     image_width/image_height;
#local cam_dist =     320;
#local cam_area =     320;
#local cam_loca =     -z * cam_dist;
#local cam_dirc =     +z * cam_dist;
#local cam_upvc =     -y * cam_area * sind(045);
#local cam_rgvc =     +x * cam_area * cam_aspc;
#local cam_tran = transform
{
	rotate		-x * 045
}
camera
{
	orthographic
	location	cam_loca
	direction	cam_dirc
	up		cam_upvc
	right		cam_rgvc
	transform {cam_tran}
}

#declare gamma_method = 3;		// 1, 2, 3 or 4

#macro gamma_color_adjust(in_color)
	#local out_gamma = 2.2;
	#local in_color = in_color + <0,0,0,0,0>;
	#if (gamma_method = 1)
		color srgbft
		<
			pow(in_color.red, out_gamma),
			pow(in_color.green, out_gamma),
			pow(in_color.blue, out_gamma),
			in_color.filter,
			in_color.transmit
		>
	#elseif (gamma_method = 2)
		color rgbft
		<
			pow(in_color.red, out_gamma),
			pow(in_color.green, out_gamma),
			pow(in_color.blue, out_gamma),
			in_color.filter,
			in_color.transmit
		>
	#elseif (gamma_method = 3)
		color srgbft in_color
	#elseif (gamma_method = 4)
		color rgbft in_color
	#end
#end

//#include "lg_color_gamma_earlier.inc"
//#include "lg_color_gamma_C3POwen.inc"
#include "lg_color_nogamma_earlier.inc"
//#include "lg_color_nogamma_C3POwen.inc"

// Lights
#declare LDXSkipLight1 = 1;
#declare LDXSkipLight2 = 1;
#declare LDXSkipLight3 = 1;
#declare LDXSkipCamera = 1;

#declare LDXQual = 1;	// Quality (0 = Bounding Box; 1 = No Refraction; 2 = Normal; 3 = Stud Logos)
#declare LDXSW = 0.5;	// Seam Width (0 for no seams)
#declare LDXStuds = 1;	// Show studs? (1 = YES; 0 = NO)
#declare LDXRefls = 1;	// Reflections? (1 = YES; 0 = NO)
#declare LDXShads = 1;	// Shadows? (1 = YES; 0 = NO)
#declare LDXFloor = 0;	// Include Floor? (1 = YES; 0 = NO)

// Model bounds information
#declare LDXMinX = -320;
#declare LDXMinY = -320;
#declare LDXMinZ = -320;
#declare LDXMaxX = 320;
#declare LDXMaxY = 320;
#declare LDXMaxZ = 320;
#declare LDXCenterX = 0;
#declare LDXCenterY = 0;
#declare LDXCenterZ = 0;
#declare LDXCenter = <LDXCenterX,LDXCenterY,LDXCenterZ>;
#declare LDXRadius = 320;

// Camera settings
#declare LDXCameraLoc = < 163.385132,-196.347702,-139.957474 >;	// Camera Location vector
#declare LDXCameraLookAt = < 10.016613492993713,9.9368115722159018,-2.9902773660520268 >;	// Camera look-at point vector
#declare LDXCameraSky = < -0.52824744758943853,-0.70597489901846244,0.47175637364122053 >;	// Camera sky vector (<0,-1,0> will usually work for standard "up")

#declare LDXFloorLoc = LDXMaxY;	// Floor location. (Dependent on floor axis; MAX_Y is bottom of model)
#declare LDXFloorAxis = y;	// Floor axis (x, y, or z)
#declare LDXFloorR = 0.8;	// Floor Red
#declare LDXFloorG = 0.8;	// Floor Green
#declare LDXFloorB = 0.8;	// Floor Blue
#declare LDXFloorAmb = 0.4;	// Floor Ambient
#declare LDXFloorDif = 0.4;	// Floor Diffuse
#declare LDXAmb = 0.4;
#declare LDXDif = 0.4;
#declare LDXRefl = 0.08;
#declare LDXPhong = 0.5;
#declare LDXPhongS = 40;
#declare LDXTRefl = 0.2;
#declare LDXTFilt = 0.85;
#declare LDXIoR = 1.25;
#declare LDXRubberRefl = 0;
#declare LDXRubberPhong = 0.1;
#declare LDXRubberPhongS = 10;
#declare LDXChromeRefl = 0.85;
#declare LDXChromeBril = 5;
#declare LDXChromeSpec = 0.8;
#declare LDXChromeRough = 0.01;
#declare LDXIPov = 1;	// Use inline POV code from LDraw file? (1 = YES; 0 = NO)
#declare LDXBgR = 0.752941;	// Background Red
#declare LDXBgG = 0.752941;	// Background Green
#declare LDXBgB = 0.752941;	// Background Blue
#declare LDXOrigVer = version;	// DO NOT MODIFY

// Camera
#ifndef (LDXSkipCamera)
camera {
	#declare LDXCamAspect = image_width/image_height;
	location LDXCameraLoc
	sky LDXCameraSky
	right LDXCamAspect * < -1,0,0 >
	look_at LDXCameraLookAt
	angle 76.360321
}
#end

// Lights
#ifndef (LDXSkipLight1)
light_source {	// Latitude,Longitude: 45,0,LDXRadius*2
	<0*LDXRadius,-1.414214*LDXRadius,-1.414214*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight2)
light_source {	// Latitude,Longitude: 30,120,LDXRadius*2
	<1.5*LDXRadius,-1*LDXRadius,0.866026*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight3)
light_source {	// Latitude,Longitude: 60,-120,LDXRadius*2
	<-0.866025*LDXRadius,-1.732051*LDXRadius,0.5*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end

#macro LDXSeamMatrix(Width, Height, Depth, CenterX, CenterY, CenterZ)
#local aw = 0;
#local ah = 0;
#local ad = 0;
#local ax = 0;
#local ay = 0;
#local az = 0;
#if (Width != 0)
#local aw = 1-LDXSW/Width;
#end
#if (Height != 0)
#local ah = 1-LDXSW/Height;
#end
#if (Depth != 0)
#local ad = 1-LDXSW/Depth;
#end
#if (Width != 0 & CenterX != 0)
#local ax = LDXSW/(Width / CenterX);
#end
#if (Height != 0 & CenterY != 0)
#local ay = LDXSW/(Height / CenterY);
#end
#if (Depth != 0 & CenterZ != 0)
#local az = LDXSW/(Depth / CenterZ);
#end
#if (aw <= 0)
#local aw = 1;
#local ax = 0;
#end
#if (ah <= 0)
#local ah = 1;
#local ay = 0;
#end
#if (ad <= 0)
#local ad = 1;
#local az = 0;
#end
matrix <aw,0,0,0,ah,0,0,0,ad,ax,ay,az>
#end


//background { color rgb <LDXBgR,LDXBgG,LDXBgB> }
background { color rgbf 1 }

#declare lg_quality = LDXQual;
#if (lg_quality = 3)
#declare lg_quality = 4;
#end

#declare lg_studs = LDXStuds;


#include "lg_defs.inc"

#ifndef (LDXColor0) // Black
#declare LDXColor0 = #if (version >= 3.1) material { #end
	texture {
		lg_black
	}
#if (version >= 3.1) } #end
#declare LDXColor0_slope = #if (version >= 3.1) material { #end
	texture {
		lg_black
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor1) // Blue
#declare LDXColor1 = #if (version >= 3.1) material { #end
	texture {
		lg_blue
	}
#if (version >= 3.1) } #end
#declare LDXColor1_slope = #if (version >= 3.1) material { #end
	texture {
		lg_blue
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor2) // Green
#declare LDXColor2 = #if (version >= 3.1) material { #end
	texture {
		lg_green
	}
#if (version >= 3.1) } #end
#declare LDXColor2_slope = #if (version >= 3.1) material { #end
	texture {
		lg_green
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor3) // Dark Turquoise
#declare LDXColor3 = #if (version >= 3.1) material { #end
	texture {
		lg_cyan
	}
#if (version >= 3.1) } #end
#declare LDXColor3_slope = #if (version >= 3.1) material { #end
	texture {
		lg_cyan
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor4) // Red
#declare LDXColor4 = #if (version >= 3.1) material { #end
	texture {
		lg_red
	}
#if (version >= 3.1) } #end
#declare LDXColor4_slope = #if (version >= 3.1) material { #end
	texture {
		lg_red
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor5) // Dark Pink
#declare LDXColor5 = #if (version >= 3.1) material { #end
	texture {
		lg_dark_pink
	}
#if (version >= 3.1) } #end
#declare LDXColor5_slope = #if (version >= 3.1) material { #end
	texture {
		lg_dark_pink
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor6) // Brown
#declare LDXColor6 = #if (version >= 3.1) material { #end
	texture {
		lg_brown
	}
#if (version >= 3.1) } #end
#declare LDXColor6_slope = #if (version >= 3.1) material { #end
	texture {
		lg_brown
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor7) // Light Gray
#declare LDXColor7 = #if (version >= 3.1) material { #end
	texture {
		lg_grey
	}
#if (version >= 3.1) } #end
#declare LDXColor7_slope = #if (version >= 3.1) material { #end
	texture {
		lg_grey
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor8) // Dark Gray
#declare LDXColor8 = #if (version >= 3.1) material { #end
	texture {
		lg_dark_grey
	}
#if (version >= 3.1) } #end
#declare LDXColor8_slope = #if (version >= 3.1) material { #end
	texture {
		lg_dark_grey
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor9) // Light Blue
#declare LDXColor9 = #if (version >= 3.1) material { #end
	texture {
		lg_light_blue
	}
#if (version >= 3.1) } #end
#declare LDXColor9_slope = #if (version >= 3.1) material { #end
	texture {
		lg_light_blue
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor10) // Bright Green
#declare LDXColor10 = #if (version >= 3.1) material { #end
	texture {
		lg_bright_green
	}
#if (version >= 3.1) } #end
#declare LDXColor10_slope = #if (version >= 3.1) material { #end
	texture {
		lg_bright_green
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor11) // Light Turquoise
#declare LDXColor11 = #if (version >= 3.1) material { #end
	texture {
		lg_turquoise
	}
#if (version >= 3.1) } #end
#declare LDXColor11_slope = #if (version >= 3.1) material { #end
	texture {
		lg_turquoise
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor12) // Salmon
#declare LDXColor12 = #if (version >= 3.1) material { #end
	texture {
		lg_salmon
	}
#if (version >= 3.1) } #end
#declare LDXColor12_slope = #if (version >= 3.1) material { #end
	texture {
		lg_salmon
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor13) // Pink
#declare LDXColor13 = #if (version >= 3.1) material { #end
	texture {
		lg_pink
	}
#if (version >= 3.1) } #end
#declare LDXColor13_slope = #if (version >= 3.1) material { #end
	texture {
		lg_pink
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor14) // Yellow
#declare LDXColor14 = #if (version >= 3.1) material { #end
	texture {
		lg_yellow
	}
#if (version >= 3.1) } #end
#declare LDXColor14_slope = #if (version >= 3.1) material { #end
	texture {
		lg_yellow
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor15) // White
#declare LDXColor15 = #if (version >= 3.1) material { #end
	texture {
		lg_white
	}
#if (version >= 3.1) } #end
#declare LDXColor15_slope = #if (version >= 3.1) material { #end
	texture {
		lg_white
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor17) // Light Green
#declare LDXColor17 = #if (version >= 3.1) material { #end
	texture {
		lg_light_green
	}
#if (version >= 3.1) } #end
#declare LDXColor17_slope = #if (version >= 3.1) material { #end
	texture {
		lg_light_green
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor18) // Light Yellow
#declare LDXColor18 = #if (version >= 3.1) material { #end
	texture {
		lg_light_yellow
	}
#if (version >= 3.1) } #end
#declare LDXColor18_slope = #if (version >= 3.1) material { #end
	texture {
		lg_light_yellow
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor19) // Tan
#declare LDXColor19 = #if (version >= 3.1) material { #end
	texture {
		lg_tan
	}
#if (version >= 3.1) } #end
#declare LDXColor19_slope = #if (version >= 3.1) material { #end
	texture {
		lg_tan
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor20) // Light Violet
#declare LDXColor20 = #if (version >= 3.1) material { #end
	texture {
		lg_light_violet
	}
#if (version >= 3.1) } #end
#declare LDXColor20_slope = #if (version >= 3.1) material { #end
	texture {
		lg_light_violet
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXSkipTransColorMacro)
#macro LDXTransColor(r, g, b)
#if (version >= 3.1) material { #end
	texture {
		pigment { #if (LDXQual > 1) rgbf <r,g,b,LDXTFilt> #else rgbf <0.6,0.6,0.6,0> #end }
#if (LDXQual > 1)
		finish { ambient LDXAmb diffuse LDXDif }
		finish { phong LDXPhong phong_size LDXPhongS reflection LDXTRefl }
		#if (version >= 3.1) #else finish { refraction 1 ior LDXIoR } #end
#end
	}
#if (version >= 3.1) #if (LDXQual > 1)
	interior { ior LDXIoR }
#end #end
#if (version >= 3.1) } #end
#end
#end

#ifndef (LDXColor21) // Glow In Dark Opaque
#declare LDXColor21 = LDXTransColor(0.987843,1,0.96902)
#end

#ifndef (LDXColor22) // Purple
#declare LDXColor22 = #if (version >= 3.1) material { #end
	texture {
		lg_purple
	}
#if (version >= 3.1) } #end
#declare LDXColor22_slope = #if (version >= 3.1) material { #end
	texture {
		lg_purple
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor23) // Dark Blue Violet
#declare LDXColor23 = #if (version >= 3.1) material { #end
	texture {
		lg_violet_blue
	}
#if (version >= 3.1) } #end
#declare LDXColor23_slope = #if (version >= 3.1) material { #end
	texture {
		lg_violet_blue
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXSkipOpaqueColorMacro)
#macro LDXOpaqueColor(r, g, b)
#if (version >= 3.1) material { #end
	texture {
		pigment { rgbf <r,g,b,0> }
#if (LDXQual > 1)
		finish { ambient LDXAmb diffuse LDXDif }
		finish { phong LDXPhong phong_size LDXPhongS reflection LDXRefl }
#end
	}
#if (version >= 3.1) } #end
#end
#end

#ifndef (LDXColor24) // Edge Colour
#declare LDXColor24 = LDXOpaqueColor(0.498039,0.498039,0.498039)
#end

#ifndef (LDXColor25) // Orange
#declare LDXColor25 = #if (version >= 3.1) material { #end
	texture {
		lg_orange
	}
#if (version >= 3.1) } #end
#declare LDXColor25_slope = #if (version >= 3.1) material { #end
	texture {
		lg_orange
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor26) // Magenta
#declare LDXColor26 = #if (version >= 3.1) material { #end
	texture {
		lg_magenta
	}
#if (version >= 3.1) } #end
#declare LDXColor26_slope = #if (version >= 3.1) material { #end
	texture {
		lg_magenta
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor27) // Lime
#declare LDXColor27 = #if (version >= 3.1) material { #end
	texture {
		lg_lime
	}
#if (version >= 3.1) } #end
#declare LDXColor27_slope = #if (version >= 3.1) material { #end
	texture {
		lg_lime
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor28) // Dark Tan
#declare LDXColor28 = #if (version >= 3.1) material { #end
	texture {
		lg_dark_tan
	}
#if (version >= 3.1) } #end
#declare LDXColor28_slope = #if (version >= 3.1) material { #end
	texture {
		lg_dark_tan
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor29) // Bright Pink
#declare LDXColor29 = #if (version >= 3.1) material { #end
	texture {
		lg_light_purple
	}
#if (version >= 3.1) } #end
#declare LDXColor29_slope = #if (version >= 3.1) material { #end
	texture {
		lg_light_purple
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor30) // Medium Lavender
#declare LDXColor30 = LDXOpaqueColor(0.67451,0.470588,0.729412)
#end

#ifndef (LDXColor31) // Lavender
#declare LDXColor31 = LDXOpaqueColor(0.882353,0.835294,0.929412)
#end

#ifndef (LDXColor32) // Trans Black IR Lens
#declare LDXColor32 = LDXTransColor(0,0,0)
#end

#ifndef (LDXColor33) // Trans Dark Blue
#declare LDXColor33 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_blue
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor33_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_blue
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor34) // Trans Green
#declare LDXColor34 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_green
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor34_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_green
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor35) // Trans Bright Green
#declare LDXColor35 = LDXTransColor(0.505882,0.990196,0.411765)
#end

#ifndef (LDXColor36) // Trans Red
#declare LDXColor36 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_red
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor36_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_red
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor37) // Trans Dark Pink
#declare LDXColor37 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_violet
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor37_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_violet
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor38) // Trans Neon Orange
#declare LDXColor38 = LDXTransColor(1,0.950196,0.076471)
#end

#ifndef (LDXColor39) // Trans Very Light Blue
#declare LDXColor39 = LDXTransColor(0.975686,0.987451,0.994118)
#end

#ifndef (LDXColor40) // Trans Black
#declare LDXColor40 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_brown
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor40_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_brown
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor41) // Trans Medium Blue
#declare LDXColor41 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_cyan
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor41_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_cyan
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor42) // Trans Neon Green
#declare LDXColor42 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_neon_yellow
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor42_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_neon_yellow
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor43) // Trans Light Blue
#declare LDXColor43 = LDXTransColor(0.968235,0.991373,0.993725)
#end

#ifndef (LDXColor44) // Trans Light Purple
#declare LDXColor44 = LDXTransColor(0.958824,0.658824,0.962353)
#end

#ifndef (LDXColor45) // Trans Pink
#declare LDXColor45 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_pink
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor45_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_pink
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor46) // Trans Yellow
#declare LDXColor46 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_yellow
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor46_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_yellow
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor47) // Trans Clear
#declare LDXColor47 = #if (version >= 3.1) material { #end
	texture {
		lg_clear
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor47_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor48) // Trans Black
#declare LDXColor48 = LDXTransColor(0.6,0.6,0.6)
#end

#ifndef (LDXColor49) // Trans Blue
#declare LDXColor49 = LDXTransColor(0,0,0.96)
#end

#ifndef (LDXColor50) // Trans Green
#declare LDXColor50 = LDXTransColor(0,0.470588,0.141176)
#end

#ifndef (LDXColor51) // Trans Dark Cyan
#declare LDXColor51 = LDXTransColor(0,0.97098,0.965098)
#end

#ifndef (LDXColor52) // Trans Purple
#declare LDXColor52 = LDXTransColor(0.964706,0.964706,0.979608)
#end

#ifndef (LDXColor53) // Trans Purple
#declare LDXColor53 = LDXTransColor(1,0.3,0.96)
#end

#ifndef (LDXColor54) // Trans Neon Yellow
#declare LDXColor54 = LDXTransColor(0.98549,0.96902,0)
#end

#ifndef (LDXColor55) // Trans Light Gray
#declare LDXColor55 = LDXTransColor(0.96,0.96,0.96)
#end

#ifndef (LDXColor56) // Trans Gray
#declare LDXColor56 = LDXTransColor(0.6,0.6,0.517647)
#end

#ifndef (LDXColor57) // Trans Orange
#declare LDXColor57 = #if (version >= 3.1) material { #end
	texture {
		lg_clear_neon_orange
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor57_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear_neon_orange
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor58) // Trans Yellow Green
#declare LDXColor58 = LDXTransColor(0.98,1,0)
#end

#ifndef (LDXColor59) // Trans Cyan
#declare LDXColor59 = LDXTransColor(0.967059,0.999216,0.997647)
#end

#ifndef (LDXSkipChromeColorMacro)
#macro LDXChromeColor(r, g, b)
#if (version >= 3.1) material { #end
	texture {
		pigment { rgbf <r,g,b,0> }
#if (LDXQual > 1)
		finish { ambient LDXAmb diffuse LDXDif }
		finish { phong LDXPhong phong_size LDXPhongS reflection LDXChromeRefl brilliance LDXChromeBril metallic specular LDXChromeSpec roughness LDXChromeRough}
#end
	}
#if (version >= 3.1) } #end
#end
#end

#ifndef (LDXColor60) // Chrome Antique Brass
#declare LDXColor60 = LDXChromeColor(0.392157,0.352941,0.298039)
#end

#ifndef (LDXColor61) // Chrome Blue
#declare LDXColor61 = LDXChromeColor(0.423529,0.588235,0.74902)
#end

#ifndef (LDXColor62) // Chrome Green
#declare LDXColor62 = LDXChromeColor(0.235294,0.701961,0.443137)
#end

#ifndef (LDXColor63) // Chrome Pink
#declare LDXColor63 = LDXChromeColor(0.666667,0.301961,0.556863)
#end

#declare LDX_axis32x_dot_dat =
#if (LDXQual = 0)
box {
	<-320,-320,-320>,<320,320,320>
}
#else
union {
// Grid - Axis 32 x 32 Color
// Name: axis32x.dat
// Author: Marc Schickele & Michael Horvath
// Unofficial Part
// Axis X
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
// Axis Y
// Axis Z
}
#end

#include "lg_3005.inc" // Brick  1 x  1

#declare LDX_color_test_dot_ldr = union {
// Untitled
// Name: color_test.ldr
// Author: Michael Horvath
// Unofficial Model
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_axis32x_dot_dat
		LDXSeamMatrix(640, 640, 640, 0, 0, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor2 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor3 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor4 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor5 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor6 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,70>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor8 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor9 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor10 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor11 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor12 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor13 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor14 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,50>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,30>
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor17 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor18 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor19 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor20 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor21 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor22 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor23 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor24 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor25 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor26 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor27 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor28 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor29 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor30 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor31 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor32 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor33 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor34 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor35 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor36 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor37 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor38 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor39 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor40 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor41 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor42 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor43 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor44 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor45 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor46 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor47 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor48 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor49 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor50 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor51 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor52 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor53 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor54 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor55 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-70,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor56 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-50,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor57 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor58 }
	}
	object {
		lg_3005_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor59 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor60 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor61 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,50,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor62 }
	}
	object {
		lg_3005
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,70,-24,-70>
		#if (version >= 3.1) material #else texture #end { LDXColor63 }
	}
#if (LDXRefls = 0)
	no_reflection
#end
#if (LDXShads = 0)
	no_shadow
#end
}

// color_test.ldr
object {
	LDX_color_test_dot_ldr
	#if (version >= 3.1) material #else texture #end { LDXColor7 }
}

// Floor
#if (LDXFloor != 0)
object {
	plane { LDXFloorAxis, LDXFloorLoc hollow }
	texture {
		pigment { color rgb <LDXFloorR,LDXFloorG,LDXFloorB> }
		finish { ambient LDXFloorAmb diffuse LDXFloorDif }
	}
}
#end

